// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// RouteTCP holds the TCP route configuration.
    /// </summary>
    public class IngressRouteTCPSpecRoutesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Match defines the router's rule. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#rule_1
        /// </summary>
        [Input("match", required: true)]
        public Input<string> Match { get; set; } = null!;

        [Input("middlewares")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteTCPSpecRoutesMiddlewaresArgs>? _middlewares;

        /// <summary>
        /// Middlewares defines the list of references to MiddlewareTCP resources.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteTCPSpecRoutesMiddlewaresArgs> Middlewares
        {
            get => _middlewares ?? (_middlewares = new InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteTCPSpecRoutesMiddlewaresArgs>());
            set => _middlewares = value;
        }

        /// <summary>
        /// Priority defines the router's priority. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#priority_1
        /// </summary>
        [Input("priority")]
        public Input<int>? Priority { get; set; }

        [Input("services")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteTCPSpecRoutesServicesArgs>? _services;

        /// <summary>
        /// Services defines the list of TCP services.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteTCPSpecRoutesServicesArgs> Services
        {
            get => _services ?? (_services = new InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteTCPSpecRoutesServicesArgs>());
            set => _services = value;
        }

        public IngressRouteTCPSpecRoutesArgs()
        {
        }
        public static new IngressRouteTCPSpecRoutesArgs Empty => new IngressRouteTCPSpecRoutesArgs();
    }
}
