// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Store defines the reference to the TLSStore, that will be used to store certificates. Please note that only `default` TLSStore can be used.
    /// </summary>
    public class IngressRouteTCPSpecTlsStoreArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name defines the name of the referenced Traefik resource.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Namespace defines the namespace of the referenced Traefik resource.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public IngressRouteTCPSpecTlsStoreArgs()
        {
        }
        public static new IngressRouteTCPSpecTlsStoreArgs Empty => new IngressRouteTCPSpecTlsStoreArgs();
    }
}
