// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Route holds the HTTP route configuration.
    /// </summary>
    public class IngressRouteSpecRoutesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Kind defines the kind of the route. Rule is the only supported kind.
        /// </summary>
        [Input("kind", required: true)]
        public Input<string> Kind { get; set; } = null!;

        /// <summary>
        /// Match defines the router's rule. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#rule
        /// </summary>
        [Input("match", required: true)]
        public Input<string> Match { get; set; } = null!;

        [Input("middlewares")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteSpecRoutesMiddlewaresArgs>? _middlewares;

        /// <summary>
        /// Middlewares defines the list of references to Middleware resources. More info: https://doc.traefik.io/traefik/v2.10/routing/providers/kubernetes-crd/#kind-middleware
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteSpecRoutesMiddlewaresArgs> Middlewares
        {
            get => _middlewares ?? (_middlewares = new InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteSpecRoutesMiddlewaresArgs>());
            set => _middlewares = value;
        }

        /// <summary>
        /// Priority defines the router's priority. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#priority
        /// </summary>
        [Input("priority")]
        public Input<int>? Priority { get; set; }

        [Input("services")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteSpecRoutesServicesArgs>? _services;

        /// <summary>
        /// Services defines the list of Service. It can contain any combination of TraefikService and/or reference to a Kubernetes Service.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteSpecRoutesServicesArgs> Services
        {
            get => _services ?? (_services = new InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.IngressRouteSpecRoutesServicesArgs>());
            set => _services = value;
        }

        public IngressRouteSpecRoutesArgs()
        {
        }
        public static new IngressRouteSpecRoutesArgs Empty => new IngressRouteSpecRoutesArgs();
    }
}
