// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// ObjectReference is a generic reference to a Traefik resource.
    /// </summary>
    public class IngressRouteTCPSpecRoutesMiddlewaresArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name defines the name of the referenced Traefik resource.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Namespace defines the namespace of the referenced Traefik resource.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public IngressRouteTCPSpecRoutesMiddlewaresArgs()
        {
        }
        public static new IngressRouteTCPSpecRoutesMiddlewaresArgs Empty => new IngressRouteTCPSpecRoutesMiddlewaresArgs();
    }
}
