// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Buffering holds the buffering middleware configuration. This middleware retries or limits the size of requests that can be forwarded to backends. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/buffering/#maxrequestbodybytes
    /// </summary>
    public class MiddlewareSpecBufferingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// MaxRequestBodyBytes defines the maximum allowed body size for the request (in bytes). If the request exceeds the allowed size, it is not forwarded to the service, and the client gets a 413 (Request Entity Too Large) response. Default: 0 (no maximum).
        /// </summary>
        [Input("maxRequestBodyBytes")]
        public Input<int>? MaxRequestBodyBytes { get; set; }

        /// <summary>
        /// MaxResponseBodyBytes defines the maximum allowed response size from the service (in bytes). If the response exceeds the allowed size, it is not forwarded to the client. The client gets a 500 (Internal Server Error) response instead. Default: 0 (no maximum).
        /// </summary>
        [Input("maxResponseBodyBytes")]
        public Input<int>? MaxResponseBodyBytes { get; set; }

        /// <summary>
        /// MemRequestBodyBytes defines the threshold (in bytes) from which the request will be buffered on disk instead of in memory. Default: 1048576 (1Mi).
        /// </summary>
        [Input("memRequestBodyBytes")]
        public Input<int>? MemRequestBodyBytes { get; set; }

        /// <summary>
        /// MemResponseBodyBytes defines the threshold (in bytes) from which the response will be buffered on disk instead of in memory. Default: 1048576 (1Mi).
        /// </summary>
        [Input("memResponseBodyBytes")]
        public Input<int>? MemResponseBodyBytes { get; set; }

        /// <summary>
        /// RetryExpression defines the retry conditions. It is a logical combination of functions with operators AND (&amp;&amp;) and OR (||). More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/buffering/#retryexpression
        /// </summary>
        [Input("retryExpression")]
        public Input<string>? RetryExpression { get; set; }

        public MiddlewareSpecBufferingArgs()
        {
        }
        public static new MiddlewareSpecBufferingArgs Empty => new MiddlewareSpecBufferingArgs();
    }
}
