// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// MiddlewareSpec defines the desired state of a Middleware.
    /// </summary>
    public class MiddlewareSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// AddPrefix holds the add prefix middleware configuration. This middleware updates the path of a request before forwarding it. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/addprefix/
        /// </summary>
        [Input("addPrefix")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecAddPrefixArgs>? AddPrefix { get; set; }

        /// <summary>
        /// BasicAuth holds the basic auth middleware configuration. This middleware restricts access to your services to known users. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/basicauth/
        /// </summary>
        [Input("basicAuth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecBasicAuthArgs>? BasicAuth { get; set; }

        /// <summary>
        /// Buffering holds the buffering middleware configuration. This middleware retries or limits the size of requests that can be forwarded to backends. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/buffering/#maxrequestbodybytes
        /// </summary>
        [Input("buffering")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecBufferingArgs>? Buffering { get; set; }

        /// <summary>
        /// Chain holds the configuration of the chain middleware. This middleware enables to define reusable combinations of other pieces of middleware. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/chain/
        /// </summary>
        [Input("chain")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecChainArgs>? Chain { get; set; }

        /// <summary>
        /// CircuitBreaker holds the circuit breaker configuration.
        /// </summary>
        [Input("circuitBreaker")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecCircuitBreakerArgs>? CircuitBreaker { get; set; }

        /// <summary>
        /// Compress holds the compress middleware configuration. This middleware compresses responses before sending them to the client, using gzip compression. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/compress/
        /// </summary>
        [Input("compress")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecCompressArgs>? Compress { get; set; }

        /// <summary>
        /// ContentType holds the content-type middleware configuration. This middleware exists to enable the correct behavior until at least the default one can be changed in a future version.
        /// </summary>
        [Input("contentType")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecContentTypeArgs>? ContentType { get; set; }

        /// <summary>
        /// DigestAuth holds the digest auth middleware configuration. This middleware restricts access to your services to known users. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/digestauth/
        /// </summary>
        [Input("digestAuth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecDigestAuthArgs>? DigestAuth { get; set; }

        /// <summary>
        /// ErrorPage holds the custom error middleware configuration. This middleware returns a custom page in lieu of the default, according to configured ranges of HTTP Status codes. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/errorpages/
        /// </summary>
        [Input("errors")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecErrorsArgs>? Errors { get; set; }

        /// <summary>
        /// ForwardAuth holds the forward auth middleware configuration. This middleware delegates the request authentication to a Service. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/forwardauth/
        /// </summary>
        [Input("forwardAuth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecForwardAuthArgs>? ForwardAuth { get; set; }

        /// <summary>
        /// Headers holds the headers middleware configuration. This middleware manages the requests and responses headers. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/headers/#customrequestheaders
        /// </summary>
        [Input("headers")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecHeadersArgs>? Headers { get; set; }

        /// <summary>
        /// InFlightReq holds the in-flight request middleware configuration. This middleware limits the number of requests being processed and served concurrently. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/inflightreq/
        /// </summary>
        [Input("inFlightReq")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecInFlightReqArgs>? InFlightReq { get; set; }

        /// <summary>
        /// IPWhiteList holds the IP whitelist middleware configuration. This middleware accepts / refuses requests based on the client IP. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/ipwhitelist/
        /// </summary>
        [Input("ipWhiteList")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecIpWhiteListArgs>? IpWhiteList { get; set; }

        /// <summary>
        /// PassTLSClientCert holds the pass TLS client cert middleware configuration. This middleware adds the selected data from the passed client TLS certificate to a header. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/passtlsclientcert/
        /// </summary>
        [Input("passTLSClientCert")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecPassTLSClientCertArgs>? PassTLSClientCert { get; set; }

        [Input("plugin")]
        private InputMap<ImmutableDictionary<string, object>>? _plugin;

        /// <summary>
        /// Plugin defines the middleware plugin configuration. More info: https://doc.traefik.io/traefik/plugins/
        /// </summary>
        public InputMap<ImmutableDictionary<string, object>> Plugin
        {
            get => _plugin ?? (_plugin = new InputMap<ImmutableDictionary<string, object>>());
            set => _plugin = value;
        }

        /// <summary>
        /// RateLimit holds the rate limit configuration. This middleware ensures that services will receive a fair amount of requests, and allows one to define what fair is. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/ratelimit/
        /// </summary>
        [Input("rateLimit")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecRateLimitArgs>? RateLimit { get; set; }

        /// <summary>
        /// RedirectRegex holds the redirect regex middleware configuration. This middleware redirects a request using regex matching and replacement. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/redirectregex/#regex
        /// </summary>
        [Input("redirectRegex")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecRedirectRegexArgs>? RedirectRegex { get; set; }

        /// <summary>
        /// RedirectScheme holds the redirect scheme middleware configuration. This middleware redirects requests from a scheme/port to another. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/redirectscheme/
        /// </summary>
        [Input("redirectScheme")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecRedirectSchemeArgs>? RedirectScheme { get; set; }

        /// <summary>
        /// ReplacePath holds the replace path middleware configuration. This middleware replaces the path of the request URL and store the original path in an X-Replaced-Path header. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/replacepath/
        /// </summary>
        [Input("replacePath")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecReplacePathArgs>? ReplacePath { get; set; }

        /// <summary>
        /// ReplacePathRegex holds the replace path regex middleware configuration. This middleware replaces the path of a URL using regex matching and replacement. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/replacepathregex/
        /// </summary>
        [Input("replacePathRegex")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecReplacePathRegexArgs>? ReplacePathRegex { get; set; }

        /// <summary>
        /// Retry holds the retry middleware configuration. This middleware reissues requests a given number of times to a backend server if that server does not reply. As soon as the server answers, the middleware stops retrying, regardless of the response status. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/retry/
        /// </summary>
        [Input("retry")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecRetryArgs>? Retry { get; set; }

        /// <summary>
        /// StripPrefix holds the strip prefix middleware configuration. This middleware removes the specified prefixes from the URL path. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/stripprefix/
        /// </summary>
        [Input("stripPrefix")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecStripPrefixArgs>? StripPrefix { get; set; }

        /// <summary>
        /// StripPrefixRegex holds the strip prefix regex middleware configuration. This middleware removes the matching prefixes from the URL path. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/stripprefixregex/
        /// </summary>
        [Input("stripPrefixRegex")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.MiddlewareSpecStripPrefixRegexArgs>? StripPrefixRegex { get; set; }

        public MiddlewareSpecArgs()
        {
        }
        public static new MiddlewareSpecArgs Empty => new MiddlewareSpecArgs();
    }
}
