// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// RedirectRegex holds the redirect regex middleware configuration. This middleware redirects a request using regex matching and replacement. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/redirectregex/#regex
    /// </summary>
    public class MiddlewareSpecRedirectRegexArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Permanent defines whether the redirection is permanent (301).
        /// </summary>
        [Input("permanent")]
        public Input<bool>? Permanent { get; set; }

        /// <summary>
        /// Regex defines the regex used to match and capture elements from the request URL.
        /// </summary>
        [Input("regex")]
        public Input<string>? Regex { get; set; }

        /// <summary>
        /// Replacement defines how to modify the URL to have the new target URL.
        /// </summary>
        [Input("replacement")]
        public Input<string>? Replacement { get; set; }

        public MiddlewareSpecRedirectRegexArgs()
        {
        }
        public static new MiddlewareSpecRedirectRegexArgs Empty => new MiddlewareSpecRedirectRegexArgs();
    }
}
