// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// DefaultGeneratedCert defines the default generated certificate configuration.
    /// </summary>
    public class TLSStoreSpecDefaultGeneratedCertArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Domain is the domain definition for the DefaultCertificate.
        /// </summary>
        [Input("domain")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TLSStoreSpecDefaultGeneratedCertDomainArgs>? Domain { get; set; }

        /// <summary>
        /// Resolver is the name of the resolver that will be used to issue the DefaultCertificate.
        /// </summary>
        [Input("resolver")]
        public Input<string>? Resolver { get; set; }

        public TLSStoreSpecDefaultGeneratedCertArgs()
        {
        }
        public static new TLSStoreSpecDefaultGeneratedCertArgs Empty => new TLSStoreSpecDefaultGeneratedCertArgs();
    }
}
