// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// TLSStoreSpec defines the desired state of a TLSStore.
    /// </summary>
    public class TLSStoreSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("certificates")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TLSStoreSpecCertificatesArgs>? _certificates;

        /// <summary>
        /// Certificates is a list of secret names, each secret holding a key/certificate pair to add to the store.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TLSStoreSpecCertificatesArgs> Certificates
        {
            get => _certificates ?? (_certificates = new InputList<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TLSStoreSpecCertificatesArgs>());
            set => _certificates = value;
        }

        /// <summary>
        /// DefaultCertificate defines the default certificate configuration.
        /// </summary>
        [Input("defaultCertificate")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TLSStoreSpecDefaultCertificateArgs>? DefaultCertificate { get; set; }

        /// <summary>
        /// DefaultGeneratedCert defines the default generated certificate configuration.
        /// </summary>
        [Input("defaultGeneratedCert")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TLSStoreSpecDefaultGeneratedCertArgs>? DefaultGeneratedCert { get; set; }

        public TLSStoreSpecArgs()
        {
        }
        public static new TLSStoreSpecArgs Empty => new TLSStoreSpecArgs();
    }
}
