// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Sticky defines whether sticky sessions are enabled. More info: https://doc.traefik.io/traefik/v2.10/routing/providers/kubernetes-crd/#stickiness-and-load-balancing
    /// </summary>
    public class TraefikServiceSpecWeightedStickyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cookie defines the sticky cookie configuration.
        /// </summary>
        [Input("cookie")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TraefikServiceSpecWeightedStickyCookieArgs>? Cookie { get; set; }

        public TraefikServiceSpecWeightedStickyArgs()
        {
        }
        public static new TraefikServiceSpecWeightedStickyArgs Empty => new TraefikServiceSpecWeightedStickyArgs();
    }
}
