apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
data:
  server.yml: |
    base-url: https://ntfy.internal.paulfriedrich.me
    listen-http: :8080
    behind-proxy: true
    cache-file: /var/cache/ntfy/cache.db
