---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: infisical-auth
spec:
  infisicalConnectionRef:
    name: infisical-connection
    namespace: infisical-operator-system
  method: universal
  universal:
    clientIdRef:
      name: infisical-credentials
      namespace: navidrome
      key: clientId
    clientSecretRef:
      name: infisical-credentials
      namespace: navidrome
      key: clientSecret
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-navidrome-config
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: navidrome
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: navidrome-gp-ox
      environmentSlug: dev
      secretPath: /navidrome
  targets:
    - name: navidrome-secrets
      namespace: navidrome
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          ND_LASTFM_APIKEY: "{{ `{{ .ND_LASTFM_APIKEY.Value }}` }}"
          ND_LASTFM_SECRET: "{{ `{{ .ND_LASTFM_SECRET.Value }}` }}"
