// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Crds.Traefik.V1Alpha1
{
    /// <summary>
    /// ServersTransport is the CRD implementation of a ServersTransport. If no serversTransport is specified, the default@internal will be used. The default@internal serversTransport is created from the static configuration. More info: https://doc.traefik.io/traefik/v2.10/routing/services/#serverstransport_1
    /// </summary>
    [CrdsResourceType("kubernetes:traefik.io/v1alpha1:ServersTransport")]
    public partial class ServersTransport : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// ServersTransportSpec defines the desired state of a ServersTransport.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.ServersTransportSpec> Spec { get; private set; } = null!;


        /// <summary>
        /// Create a ServersTransport resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServersTransport(string name, Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.ServersTransportArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:traefik.io/v1alpha1:ServersTransport", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal ServersTransport(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:traefik.io/v1alpha1:ServersTransport", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private ServersTransport(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:traefik.io/v1alpha1:ServersTransport", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.ServersTransportArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.ServersTransportArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.ServersTransportArgs();
            args.ApiVersion = "traefik.io/v1alpha1";
            args.Kind = "ServersTransport";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServersTransport resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServersTransport Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ServersTransport(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    public class ServersTransportArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// ServersTransportSpec defines the desired state of a ServersTransport.
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.ServersTransportSpecArgs>? Spec { get; set; }

        public ServersTransportArgs()
        {
        }
        public static new ServersTransportArgs Empty => new ServersTransportArgs();
    }
}
