// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Crds.Traefik.V1Alpha1
{
    /// <summary>
    /// TraefikService is the CRD implementation of a Traefik Service. TraefikService object allows to: - Apply weight to Services on load-balancing - Mirror traffic on services More info: https://doc.traefik.io/traefik/v2.10/routing/providers/kubernetes-crd/#kind-traefikservice
    /// </summary>
    [CrdsResourceType("kubernetes:traefik.io/v1alpha1:TraefikService")]
    public partial class TraefikService : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// TraefikServiceSpec defines the desired state of a TraefikService.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.TraefikServiceSpec> Spec { get; private set; } = null!;


        /// <summary>
        /// Create a TraefikService resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TraefikService(string name, Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TraefikServiceArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:traefik.io/v1alpha1:TraefikService", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal TraefikService(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:traefik.io/v1alpha1:TraefikService", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private TraefikService(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:traefik.io/v1alpha1:TraefikService", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TraefikServiceArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TraefikServiceArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TraefikServiceArgs();
            args.ApiVersion = "traefik.io/v1alpha1";
            args.Kind = "TraefikService";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TraefikService resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TraefikService Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new TraefikService(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1
{

    public class TraefikServiceArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// TraefikServiceSpec defines the desired state of a TraefikService.
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Traefik.V1Alpha1.TraefikServiceSpecArgs>? Spec { get; set; }

        public TraefikServiceArgs()
        {
        }
        public static new TraefikServiceArgs Empty => new TraefikServiceArgs();
    }
}
