apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-redis-config
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: livekit
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: livekit-poi3
      environmentSlug: dev
      secretPath: /redis
  targets:
    - name: redis-secrets
      namespace: livekit
      kind: Secret
      creationPolicy: Owner
