keys:
  - &pfriedrich age1jxmmkdzm0gas4z03q6mnzcv5exs7wlxjxrp8qzh0eujzqk8wvvyqk3qcjy
  - &e595 age1yudlqm69y6jl6vy45fvl8u0kfzp9f7fzrmh5n98muxlj5j6weutq9ckk2e
  - &tailscale01 age16w0xprw344h2f388jcdj4xydd8evjgrchz9uqmq552cf4v65fg3q44p67j
  - &nomadserver01 age15v6yvntsk9zfmlghkpuspncx2g6p065nqj8zejgau0dcq6ntxfus4pr0ta
  - &nomadserver02 age1z4t8p382904qv0rhqj8clp6yzm772k33fc5danvcs25eatkrz50q66s8vp
  - &nomadserver03 age1xct5l7uzzvw6jyse5xv4uegtmg3nzmtye60jcw6rmmp77fq2gvys2h58vq
  - &nomadclient01 age1llsz23rl6hhjl9ls5ax29hrg7qzghfa6zvhayt70ls3zm5gjysrq3vsyng
  - &storage age1cft5ex8pc5hn75f4dyraad4qr25lcsnvtac3ss3nv29n5slxepqqqckkn9
  - &stepca age135rrse02t76trsm53za7jg9teuwt9e4mqvamyalkudhyydgh6e9qfe8xcw
  - &flux age1qkxcnuwjvme9667c763xpxjedfyxjpgl09msty80esrf3fuj45cqeh9v6q
creation_rules:
  - path_regex: secrets/e595\.yaml$
    key_groups:
      - age:
        - *pfriedrich
        - *e595
  - path_regex: secrets/tailscale01\.yaml$
    key_groups:
      - age:
        - *pfriedrich
        - *tailscale01
  - path_regex: secrets/nomadserver\.yaml$
    key_groups:
      - age:
        - *pfriedrich
        - *nomadserver01
        - *nomadserver02
        - *nomadserver03
  - path_regex: secrets/nomadclient\.yaml$
    key_groups:
      - age:
        - *pfriedrich
        - *nomadclient01
  - path_regex: secrets/storage\.yaml$
    key_groups:
      - age:
        - *pfriedrich
        - *storage
  - path_regex: secrets/stepca\.yaml$
    key_groups:
      - age:
        - *pfriedrich
        - *stepca
  - path_regex: kubernetes/talos/talsecret.sops.yaml
    key_groups:
      - age:
        - *pfriedrich
  - path_regex: kubernetes/.*\.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
        - *pfriedrich
        - *flux

