---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - ../../base
  - vaultwarden.yaml
  - httproute.yaml

images:
  - name: ghcr.io/dani-garcia/vaultwarden
    newTag: 1.34.1
