---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omada-controller

resources:
  - ../../base
  - omada-controller.yaml
  - httproute.yaml

images:
  - name: mbentley/omada-controller
    newTag: "5.14-chromium"
