---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-internal-paulfriedrich-me
spec:
  secretName: wildcard-internal-paulfriedrich-me-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.internal.paulfriedrich.me"
