apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-restic-config
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: continuwuity
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: continuwuity-rca-b
      environmentSlug: dev
      secretPath: /restic
  targets:
    - name: restic-config
      namespace: continuwuity
      kind: Secret
      creationPolicy: Owner
