// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Crds.K8up.V1
{
    /// <summary>
    /// Check is the Schema for the checks API
    /// </summary>
    [CrdsResourceType("kubernetes:k8up.io/v1:Check")]
    public partial class Check : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// CheckSpec defines the desired state of Check. It needs to contain the repository information.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.K8up.V1.CheckSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// Status defines the observed state of a generic K8up job. It is used for the operator to determine what to do.
        /// </summary>
        [Output("status")]
        public Output<Pulumi.Kubernetes.Types.Outputs.K8up.V1.CheckStatus> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Check resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Check(string name, Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:k8up.io/v1:Check", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal Check(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:k8up.io/v1:Check", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private Check(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:k8up.io/v1:Check", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckArgs();
            args.ApiVersion = "k8up.io/v1";
            args.Kind = "Check";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Check resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Check Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Check(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    public class CheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// CheckSpec defines the desired state of Check. It needs to contain the repository information.
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckSpecArgs>? Spec { get; set; }

        /// <summary>
        /// Status defines the observed state of a generic K8up job. It is used for the operator to determine what to do.
        /// </summary>
        [Input("status")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckStatusArgs>? Status { get; set; }

        public CheckArgs()
        {
        }
        public static new CheckArgs Empty => new CheckArgs();
    }
}
