// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Route holds the HTTP route configuration.
    /// </summary>
    [OutputType]
    public sealed class IngressRouteSpecRoutes
    {
        /// <summary>
        /// Kind defines the kind of the route. Rule is the only supported kind.
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Match defines the router's rule. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#rule
        /// </summary>
        public readonly string Match;
        /// <summary>
        /// Middlewares defines the list of references to Middleware resources. More info: https://doc.traefik.io/traefik/v2.10/routing/providers/kubernetes-crd/#kind-middleware
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecRoutesMiddlewares> Middlewares;
        /// <summary>
        /// Priority defines the router's priority. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#priority
        /// </summary>
        public readonly int Priority;
        /// <summary>
        /// Services defines the list of Service. It can contain any combination of TraefikService and/or reference to a Kubernetes Service.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecRoutesServices> Services;

        [OutputConstructor]
        private IngressRouteSpecRoutes(
            string kind,

            string match,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecRoutesMiddlewares> middlewares,

            int priority,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecRoutesServices> services)
        {
            Kind = kind;
            Match = match;
            Middlewares = middlewares;
            Priority = priority;
            Services = services;
        }
    }
}
