// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// TLS defines the TLS configuration. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#tls
    /// </summary>
    [OutputType]
    public sealed class IngressRouteSpecTls
    {
        /// <summary>
        /// CertResolver defines the name of the certificate resolver to use. Cert resolvers have to be configured in the static configuration. More info: https://doc.traefik.io/traefik/v2.10/https/acme/#certificate-resolvers
        /// </summary>
        public readonly string CertResolver;
        /// <summary>
        /// Domains defines the list of domains that will be used to issue certificates. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#domains
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTlsDomains> Domains;
        /// <summary>
        /// Options defines the reference to a TLSOption, that specifies the parameters of the TLS connection. If not defined, the `default` TLSOption is used. More info: https://doc.traefik.io/traefik/v2.10/https/tls/#tls-options
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTlsOptions Options;
        /// <summary>
        /// SecretName is the name of the referenced Kubernetes Secret to specify the certificate details.
        /// </summary>
        public readonly string SecretName;
        /// <summary>
        /// Store defines the reference to the TLSStore, that will be used to store certificates. Please note that only `default` TLSStore can be used.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTlsStore Store;

        [OutputConstructor]
        private IngressRouteSpecTls(
            string certResolver,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTlsDomains> domains,

            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTlsOptions options,

            string secretName,

            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTlsStore store)
        {
            CertResolver = certResolver;
            Domains = domains;
            Options = options;
            SecretName = secretName;
            Store = store;
        }
    }
}
