// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Store defines the reference to the TLSStore, that will be used to store certificates. Please note that only `default` TLSStore can be used.
    /// </summary>
    [OutputType]
    public sealed class IngressRouteTCPSpecTlsStore
    {
        /// <summary>
        /// Name defines the name of the referenced Traefik resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Namespace defines the namespace of the referenced Traefik resource.
        /// </summary>
        public readonly string Namespace;

        [OutputConstructor]
        private IngressRouteTCPSpecTlsStore(
            string name,

            string @namespace)
        {
            Name = name;
            Namespace = @namespace;
        }
    }
}
