// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// IngressRouteSpec defines the desired state of IngressRoute.
    /// </summary>
    [OutputType]
    public sealed class IngressRouteSpec
    {
        /// <summary>
        /// EntryPoints defines the list of entry point names to bind to. Entry points have to be configured in the static configuration. More info: https://doc.traefik.io/traefik/v2.10/routing/entrypoints/ Default: all.
        /// </summary>
        public readonly ImmutableArray<string> EntryPoints;
        /// <summary>
        /// Routes defines the list of routes.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecRoutes> Routes;
        /// <summary>
        /// TLS defines the TLS configuration. More info: https://doc.traefik.io/traefik/v2.10/routing/routers/#tls
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTls Tls;

        [OutputConstructor]
        private IngressRouteSpec(
            ImmutableArray<string> entryPoints,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecRoutes> routes,

            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.IngressRouteSpecTls tls)
        {
            EntryPoints = entryPoints;
            Routes = routes;
            Tls = tls;
        }
    }
}
