// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Domain holds a domain name with SANs.
    /// </summary>
    [OutputType]
    public sealed class IngressRouteSpecTlsDomains
    {
        /// <summary>
        /// Main defines the main domain name.
        /// </summary>
        public readonly string Main;
        /// <summary>
        /// SANs defines the subject alternative domain names.
        /// </summary>
        public readonly ImmutableArray<string> Sans;

        [OutputConstructor]
        private IngressRouteSpecTlsDomains(
            string main,

            ImmutableArray<string> sans)
        {
            Main = main;
            Sans = sans;
        }
    }
}
