// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// RedirectRegex holds the redirect regex middleware configuration. This middleware redirects a request using regex matching and replacement. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/redirectregex/#regex
    /// </summary>
    [OutputType]
    public sealed class MiddlewareSpecRedirectRegex
    {
        /// <summary>
        /// Permanent defines whether the redirection is permanent (301).
        /// </summary>
        public readonly bool Permanent;
        /// <summary>
        /// Regex defines the regex used to match and capture elements from the request URL.
        /// </summary>
        public readonly string Regex;
        /// <summary>
        /// Replacement defines how to modify the URL to have the new target URL.
        /// </summary>
        public readonly string Replacement;

        [OutputConstructor]
        private MiddlewareSpecRedirectRegex(
            bool permanent,

            string regex,

            string replacement)
        {
            Permanent = permanent;
            Regex = regex;
            Replacement = replacement;
        }
    }
}
