// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// ReplacePath holds the replace path middleware configuration. This middleware replaces the path of the request URL and store the original path in an X-Replaced-Path header. More info: https://doc.traefik.io/traefik/v2.10/middlewares/http/replacepath/
    /// </summary>
    [OutputType]
    public sealed class MiddlewareSpecReplacePath
    {
        /// <summary>
        /// Path defines the path to use as replacement in the request URL.
        /// </summary>
        public readonly string Path;

        [OutputConstructor]
        private MiddlewareSpecReplacePath(string path)
        {
            Path = path;
        }
    }
}
