// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// MiddlewareTCPSpec defines the desired state of a MiddlewareTCP.
    /// </summary>
    [OutputType]
    public sealed class MiddlewareTCPSpec
    {
        /// <summary>
        /// InFlightConn defines the InFlightConn middleware configuration.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.MiddlewareTCPSpecInFlightConn InFlightConn;
        /// <summary>
        /// IPWhiteList defines the IPWhiteList middleware configuration.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.MiddlewareTCPSpecIpWhiteList IpWhiteList;

        [OutputConstructor]
        private MiddlewareTCPSpec(
            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.MiddlewareTCPSpecInFlightConn inFlightConn,

            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.MiddlewareTCPSpecIpWhiteList ipWhiteList)
        {
            InFlightConn = inFlightConn;
            IpWhiteList = ipWhiteList;
        }
    }
}
