// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// Subject defines the client certificate subject details to add to the X-Forwarded-Tls-Client-Cert-Info header.
    /// </summary>
    [OutputType]
    public sealed class MiddlewareSpecPassTLSClientCertInfoSubject
    {
        /// <summary>
        /// CommonName defines whether to add the organizationalUnit information into the subject.
        /// </summary>
        public readonly bool CommonName;
        /// <summary>
        /// Country defines whether to add the country information into the subject.
        /// </summary>
        public readonly bool Country;
        /// <summary>
        /// DomainComponent defines whether to add the domainComponent information into the subject.
        /// </summary>
        public readonly bool DomainComponent;
        /// <summary>
        /// Locality defines whether to add the locality information into the subject.
        /// </summary>
        public readonly bool Locality;
        /// <summary>
        /// Organization defines whether to add the organization information into the subject.
        /// </summary>
        public readonly bool Organization;
        /// <summary>
        /// OrganizationalUnit defines whether to add the organizationalUnit information into the subject.
        /// </summary>
        public readonly bool OrganizationalUnit;
        /// <summary>
        /// Province defines whether to add the province information into the subject.
        /// </summary>
        public readonly bool Province;
        /// <summary>
        /// SerialNumber defines whether to add the serialNumber information into the subject.
        /// </summary>
        public readonly bool SerialNumber;

        [OutputConstructor]
        private MiddlewareSpecPassTLSClientCertInfoSubject(
            bool commonName,

            bool country,

            bool domainComponent,

            bool locality,

            bool organization,

            bool organizationalUnit,

            bool province,

            bool serialNumber)
        {
            CommonName = commonName;
            Country = country;
            DomainComponent = domainComponent;
            Locality = locality;
            Organization = organization;
            OrganizationalUnit = organizationalUnit;
            Province = province;
            SerialNumber = serialNumber;
        }
    }
}
