// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// ServersTransportSpec defines the desired state of a ServersTransport.
    /// </summary>
    [OutputType]
    public sealed class ServersTransportSpec
    {
        /// <summary>
        /// CertificatesSecrets defines a list of secret storing client certificates for mTLS.
        /// </summary>
        public readonly ImmutableArray<string> CertificatesSecrets;
        /// <summary>
        /// DisableHTTP2 disables HTTP/2 for connections with backend servers.
        /// </summary>
        public readonly bool DisableHTTP2;
        /// <summary>
        /// ForwardingTimeouts defines the timeouts for requests forwarded to the backend servers.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.ServersTransportSpecForwardingTimeouts ForwardingTimeouts;
        /// <summary>
        /// InsecureSkipVerify disables SSL certificate verification.
        /// </summary>
        public readonly bool InsecureSkipVerify;
        /// <summary>
        /// MaxIdleConnsPerHost controls the maximum idle (keep-alive) to keep per-host.
        /// </summary>
        public readonly int MaxIdleConnsPerHost;
        /// <summary>
        /// PeerCertURI defines the peer cert URI used to match against SAN URI during the peer certificate verification.
        /// </summary>
        public readonly string PeerCertURI;
        /// <summary>
        /// RootCAsSecrets defines a list of CA secret used to validate self-signed certificate.
        /// </summary>
        public readonly ImmutableArray<string> RootCAsSecrets;
        /// <summary>
        /// ServerName defines the server name used to contact the server.
        /// </summary>
        public readonly string ServerName;

        [OutputConstructor]
        private ServersTransportSpec(
            ImmutableArray<string> certificatesSecrets,

            bool disableHTTP2,

            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.ServersTransportSpecForwardingTimeouts forwardingTimeouts,

            bool insecureSkipVerify,

            int maxIdleConnsPerHost,

            string peerCertURI,

            ImmutableArray<string> rootCAsSecrets,

            string serverName)
        {
            CertificatesSecrets = certificatesSecrets;
            DisableHTTP2 = disableHTTP2;
            ForwardingTimeouts = forwardingTimeouts;
            InsecureSkipVerify = insecureSkipVerify;
            MaxIdleConnsPerHost = maxIdleConnsPerHost;
            PeerCertURI = peerCertURI;
            RootCAsSecrets = rootCAsSecrets;
            ServerName = serverName;
        }
    }
}
