// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1
{

    /// <summary>
    /// TraefikServiceSpec defines the desired state of a TraefikService.
    /// </summary>
    [OutputType]
    public sealed class TraefikServiceSpec
    {
        /// <summary>
        /// Mirroring defines the Mirroring service configuration.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.TraefikServiceSpecMirroring Mirroring;
        /// <summary>
        /// Weighted defines the Weighted Round Robin configuration.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.TraefikServiceSpecWeighted Weighted;

        [OutputConstructor]
        private TraefikServiceSpec(
            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.TraefikServiceSpecMirroring mirroring,

            Pulumi.Kubernetes.Types.Outputs.Traefik.V1Alpha1.TraefikServiceSpecWeighted weighted)
        {
            Mirroring = mirroring;
            Weighted = weighted;
        }
    }
}
