---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-node-manual
spec:
  interval: 10m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 15m
  values:
    csiDriver:
      name: org.democratic-csi.node-manual
    controller:
      enabled: false
    driver:
      config:
        driver: node-manual