---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCK4JmA9Chz1NsN5mGEzDnKHzCODp9WG1JjBneRWMRxIfmH2SLmRQGjiK+mFOIolLND42AZ47amyL29H/PSsCf+anS41gU4l5Fsuju96//lfd11smFCQo6nQ1B9pE4jN/LREsRyzQw/0YAdqOZFHOcNACJFbav59/XxQn818IRtavvmuiZj2fE87S49KLeaYDs1lOSRLzM/9SKzdTmbGccTMnP8XUKhKDXLtpgi/2POtqf+eMNsGg7ajMy3W7KHpQWDa4LNL1o6kZMEUxqQ+K9C1yjW8ePRGJ+XwcUbC+DloLEZ2TqJEKXSKyfrlgrBPcuNg2YU61Pz4eg99/hUdUv8dS2w5cdb914pWoyTKr+0P3dFv3guy5MNfttEGJ7FURIXDM/3N3ZuvGl1FGxhPN3NG7kjkPKi4R19gtaZTy+mqULOh281fRsM1sdvgklfpj/tJIrp7M5C2rLjKe2iZzyPM5tiIpVIAZQpO/0AADW6fkws90+8cGX+XO1RjjqxGbcUZFWcvjOQQnyXr395DevNPy4dMN83W3Edn61r1fXoPU75MaIqrzi8tR8UHewiVynV3CzLCcsenCjN08Lqmo8fJExv73MQCYtFb+OqhM3N+1A2awP7yR7YsuCm50NuPgI9ow0cQ6cE8kqQDY/oJTdSmLJDUBxKmWoSL52ovgCf2xKwmvtlysabb8g/K1/oYlTx2vp2LZnxbOeMW8MfAEMt1Lj8bCB2hQsul3kijdYLaS27QisXyBiT
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
