apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: infisical-auth
spec:
  infisicalConnectionRef:
    name: infisical-connection
    namespace: infisical-operator-system
  method: universal
  universal:
    clientIdRef:
      name: infisical-credentials
      namespace: cert-manager
      key: clientId
    clientSecretRef:
      name: infisical-credentials
      namespace: cert-manager
      key: clientSecret
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-restic-config
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: cert-manager
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: cert-manager-tq-jt
      environmentSlug: dev
      secretPath: /
  targets:
    - name: cert-manager-secrets
      namespace: cert-manager
      kind: Secret
      creationPolicy: Owner
