netbox:
  superuser:
    existingSecret: superuser-secret
  existingSecret: config-secret

  powerFeedDefaultVoltage: 240
  powerFeedDefaultAmperate: 16

  persistence:
    enabled: false

  email:
    username: mail@paulfriedrich.me
    server: smtp.fastmail.com
    port: 456
    useSSL: true
    from: netbox@mail.paulfriedrich.me

  postgresql:
    auth:
      existingSecret: "postgres-auth"

  redis:
    auth:
      existingSecret: "redis-auth"
      existingSecretPasswordKey: "redis-password"
