---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: ${CLOUDFLARE_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          cloudflare:
            email: ${CLOUDFLARE_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
