---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sabnzbd-downloads
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: 9a5946cb-88ad-4f21-a80c-ec8f5ec25152
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/downloads
      node_attach_driver: nfs
      provisioner_driver: node-manual
