apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HFNbLo+VM2WL8DjYt/KCvJFa0IrIKuGnqQlMXjwwQWE=,iv:q5Jp6naje5tT3GXZK6Ij6bXGq4PGPC4r9yzpsaIfZMw=,tag:JLPh6S+Qo0MJpw0Ph6OZ0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxmmkdzm0gas4z03q6mnzcv5exs7wlxjxrp8qzh0eujzqk8wvvyqk3qcjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWCtwd1BOb3hvNXFHWnpt
            T3NwcTdZWE9jWWlCeTJ0WW8rdEhMc3BSRzBJCmZsWTlnWjA3N0VTUDNwbTArWUN0
            d0JzcjVXbGZ4UGxJb3BWdnl0QktzNE0KLS0tIGpacXBLYnRuRmo1alBGUUxka0w5
            bkthV0c4eStJNlpob2I0NHVOVUdGeTgKFeze2h28nqp3/4pD7C00rJQQIamqz9eA
            undtRfC8t/epq/Yi4d8OniViJBC5CqxupVIQnsJ2ncmL2ZOaHsnkUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qkxcnuwjvme9667c763xpxjedfyxjpgl09msty80esrf3fuj45cqeh9v6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWTR5bkl2UkpIKzA4aHJj
            eHlUNDJnL3RNLzNDcmkvT0J6RkRFOWdIUVRFCmRKRTltVHpBa0d6R0QwYmRJVHR6
            cjBQcHgzNkwxWGFrbnVaT1hBV0s5amcKLS0tIGZ4cHZpSzlhMDhwdCsvSC9uVHR3
            aFpEaUFidE5MZUp6d3lIUnZabUl3djAK/O/6J/a+LyFcuuy5UthEkYF70gBzTfcO
            kBCmKPh5Huy5uqEulCzR6ocA0qW+3LT9ynE0fGC5hhEdMvZruz+EEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T14:13:09Z"
    mac: ENC[AES256_GCM,data:3KfGjO04QnxDGTYjXviVFtKBaK2eie8fUsxC8HGwjUmWVue625HRd5e8TFUgNpaDEQLnFPRVc04mZphGJAWJFrdjYcyTyi3U4Hr0ibTOruG7VG9gOFckCXQk5BUCoBDQOIP0GfpoMTouIHw+xFgl5GDY+E+VzINUZ4aWqelo1Q4=,iv:EwsyXQGbkenedaKHTlvbpRoIcQUwRZ4ngJLkQTHbwB4=,tag:lHfopDfhZcI/vmrz8S4nVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
