apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HFNbLo+VM2WL8DjYt/KCvJFa0IrIKuGnqQlMXjwwQWE=,iv:q5Jp6naje5tT3GXZK6Ij6bXGq4PGPC4r9yzpsaIfZMw=,tag:JLPh6S+Qo0MJpw0Ph6OZ0Q==,type:str]
    TRUENAS_DEMOCRATIC_CSI_API_KEY: ENC[AES256_GCM,data:gcdWNQalHeZgOW9YerewIfikDD7WruPaUomUqmSl4c7/TsbDK6KvLNBQnVA0RATgpfLjgiWyRjHFI8nQjGHPmWa3,iv:KQ1/5Y/KgKsBuL5irJ7EgCW3JjCr3T6ds1SUdYuAZw4=,tag:MqiIME7ksn5VIzNCfUo0IA==,type:str]
    TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME: ENC[AES256_GCM,data:3NyMe99deajs,iv:Yd2Ga9vwBTajx5TjanP/J538DLM9iyZdjjrwZWFJzwM=,tag:FckiL8sjNIzESKeCiRXt1Q==,type:str]
    TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD: ENC[AES256_GCM,data:rnge5mnjCwk274iNmbgSMQ==,iv:50hpYpJDM8P2XpypFt1OCvX0gwu/QJft+M9LqvNlFeI=,tag:fTDlroKofMx4pftTo5vhUA==,type:str]
    TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME_IN: ENC[AES256_GCM,data:l1rqgVQ6rPXd,iv:cPODpCJX3y8eH7ZHCMvtpSIRYFHOKEtmUcpHP/gq4Zg=,tag:rvHnAbTWYms1uPoIiPY+2w==,type:str]
    TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD_IN: ENC[AES256_GCM,data:hgfj03JRi2nAbEJA7UkpVA==,iv:b93aRkQjqR7qtWyd/qNysqJhS4fcylqw25cqCtBzTYU=,tag:TtBm/tyyE6Bx4D0L1bvFjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxmmkdzm0gas4z03q6mnzcv5exs7wlxjxrp8qzh0eujzqk8wvvyqk3qcjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWCtwd1BOb3hvNXFHWnpt
            T3NwcTdZWE9jWWlCeTJ0WW8rdEhMc3BSRzBJCmZsWTlnWjA3N0VTUDNwbTArWUN0
            d0JzcjVXbGZ4UGxJb3BWdnl0QktzNE0KLS0tIGpacXBLYnRuRmo1alBGUUxka0w5
            bkthV0c4eStJNlpob2I0NHVOVUdGeTgKFeze2h28nqp3/4pD7C00rJQQIamqz9eA
            undtRfC8t/epq/Yi4d8OniViJBC5CqxupVIQnsJ2ncmL2ZOaHsnkUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qkxcnuwjvme9667c763xpxjedfyxjpgl09msty80esrf3fuj45cqeh9v6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWTR5bkl2UkpIKzA4aHJj
            eHlUNDJnL3RNLzNDcmkvT0J6RkRFOWdIUVRFCmRKRTltVHpBa0d6R0QwYmRJVHR6
            cjBQcHgzNkwxWGFrbnVaT1hBV0s5amcKLS0tIGZ4cHZpSzlhMDhwdCsvSC9uVHR3
            aFpEaUFidE5MZUp6d3lIUnZabUl3djAK/O/6J/a+LyFcuuy5UthEkYF70gBzTfcO
            kBCmKPh5Huy5uqEulCzR6ocA0qW+3LT9ynE0fGC5hhEdMvZruz+EEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-01T14:04:11Z"
    mac: ENC[AES256_GCM,data:GWewfdF1VIwLHgX2YU1GmJzd2et/ckPqnB94xxdgT408+NqenMDPcGhhGoQkrQeQg1ngUMUdkI7OvaFZE9+YxJE2ZwVmdfJJTncVXdRNbmVxP2H68i09XVT5nECZVZ+LTYotFKFPQXGFCKsHnyfrwRI70qAlF5z2x0E7dzvOWhc=,iv:CpukIc65hmB+42Bo2p28e2TiqQYJ+s/bTJ7rVk5rfN0=,tag:8D5dfk+XV/EgUpC7YSSGLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
