apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: infisical-auth
spec:
  infisicalConnectionRef:
    name: infisical-connection
    namespace: infisical-operator-system
  method: universal
  universal:
    clientIdRef:
      name: infisical-credentials
      namespace: livekit
      key: clientId
    clientSecretRef:
      name: infisical-credentials
      namespace: livekit
      key: clientSecret
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-livekit-config
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: livekit
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: livekit-poi3
      environmentSlug: dev
      secretPath: /
      recursive: true
  targets:
    - name: livekit-secrets
      namespace: livekit
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          LIVEKIT_URL: "{{ `{{ .LIVEKIT_URL.Value }}` }}"
          LIVEKIT_MATRIX_KEY: "{{ `{{ .LIVEKIT_MATRIX_KEY.Value }}` }}"
          LIVEKIT_MATRIX_TOKEN: "{{ `{{ .LIVEKIT_MATRIX_TOKEN.Value }}` }}"
          LIVEKIT_FULL_ACCESS_HOMESERVERS: "{{ `{{ .LIVEKIT_FULL_ACCESS_HOMESERVERS.Value }}` }}"
    - name: livekit-config
      namespace: livekit
      kind: ConfigMap
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          CONFIG: |
            log_level: info
            port: 7880

            keys:
              access_token: {{ `{{ .LIVEKIT_ACCESS_TOKEN.Value }}` }}
              {{ `{{ .LIVEKIT_MATRIX_KEY.Value }}` }}: {{ `{{ .LIVEKIT_MATRIX_TOKEN.Value }}` }}

            redis:
              address: livekit-redis.livekit.svc.cluster.local:6379

            rtc:
              tcp_port: 7881
              port_range_start: 50000
              port_range_end: 60000
              use_external_ip: false

              stun_servers:
                - {{ `{{ .STUNNER_IP.Value }}` }}:3478

              turn_servers:
                - host: {{ `{{ .STUNNER_IP.Value }}` }}
                  port: 3478
                  protocol: udp
                  username: {{ `{{ .STUNNER_USERNAME.Value }}` }}
                  credential: {{ `{{ .STUNNER_PASSWORD.Value }}` }}

            turn:
              enabled: false
              loadBalancerAnnotations: {}
