---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-auth
  namespace: netbox
spec:
  encryptedData:
    password: AgBCtsifOh3CoHouRbaI0d8nOzJ8bLXzSetyCnXgamWVAM2L78BOh2DXM6Go5GxVt2EQg/EaFn48I3I9gySXvtVnCRAlUZFl5awngMjiF/uSm/yJ17WVJROzuC0a13mtyH8boSEvBdG+ahlQNHFOZUZtpBlmH79cq2OMGtk0KKH5r0T4VCi+f34iYoQFfXtkRjN2jrkXr2QW0wiGOATrsvVymScG+Dv4l2UPwNsaj2aK4pDbs/eNcIYGMFMQwQU3ekEzSXqtcIOlhTnAkEwi8EQ+00furxPNx3BHTqwk97DRB2unE++PBlxba6bbFsqpPbRTdDUdatiS5REq2C0PskWGcitpDSev3CVAL7jxnodIKGjgGobOPs+oH0IOl7pSOZow/XS2bbyxK/9wnoTt9O7wqb2WAwsNy4a6BMW0DKOIOfJ0B2aFoJlnnzQdBgG4S8PDdhmbvaJDzCuidA2pbVKfpLgWpfMbVh67H0DY2m6dEXWeLEPNp3mR6vWiJ1VUMlw1yXdtCvI7jjMCQ/Fxn2Jf/CQFE1C6fxe8pvj67/zYztHWillmqGw0pUN7TpB8xrkTrM0PEJvKVx7smHYlLSzocsImOvuGrUTkCmTa//qDPZbzjyX31nPShpOoEMQHRVt2eKutST4TME304O5UGqc0Q4ifTLQwHiNub4YtCJFaiyS8mat7CaVOgA2Q1kcTZzheiMg6cFoCZDga
    postgres-password: AgCkfRHnDq8ei3s4jorFCnZp75SOvT9u15vde66yZ5KtEx3rZWR17mHp4cvfr3nS+dXgp5+UfIys78L0B5bEpAKlBltWBdGpYvewf628FlKR+4QkURuT086YTXJFwTPqoFd6IcPgcgTaNc1F4T6QBnNoGouW/1dWU7r4wvQ3swtdMOdjnJmlbGui+2oTgoS51s4U6qCJjBKwbjLDE+i6CFEqfXKDFQ2ep7DKBgzwamO3u6hPlgTAgp1oJ7hGcnsB21cTjT2rO8w2x1RNsphNHAXeHU6BbhsFnWcerFOPqN+IXp2hyp0DoIfqzdgAer8ebTYlxNHXM6LQPJ3X2si/J+/YWwUbu8sNgZasDDmkwgXP+CVtFMXcRzxtXBv5R8rvBERPCZK7cY4a0k2TG79tMJhIbNJwNKPIhGXCzADVDuwa5mJQzZAorOTb4i21ySJ0embOIUdWRH5MYSS6EUl0OrHPndkkdu4vIGEyUBE4cxQD9MAxM43S4z1ihTny/ZvQqdT3iTIWGCFgp2o2V0TA4aS48N0+xc0rV6sLikGBJzXhLZmC+KqdQd1WSnmOvDBA/A9tnx4I0aCJGZTfGh/1eAd/VkdyMbxe+M13ujY64or/HEdRasqBnz9lGIk2ddoPH2r6KtmOla1Ba3Mj7mT4YBc+1iGohjKinNldKBqSpIpAFzrJ5ZSpuO30/J+84eO6IoFZnRk2Eay6jKWL
  template:
    metadata:
      creationTimestamp: null
      name: postgres-auth
      namespace: netbox
