// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    public class CheckSpecBackendAzureArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("accountKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckSpecBackendAzureAccountKeySecretRefArgs>? AccountKeySecretRef { get; set; }

        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("accountNameSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.CheckSpecBackendAzureAccountNameSecretRefArgs>? AccountNameSecretRef { get; set; }

        [Input("container")]
        public Input<string>? Container { get; set; }

        public CheckSpecBackendAzureArgs()
        {
        }
        public static new CheckSpecBackendAzureArgs Empty => new CheckSpecBackendAzureArgs();
    }
}
