// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    /// <summary>
    /// EffectiveScheduleSpec defines the desired state of EffectiveSchedule
    /// </summary>
    public class EffectiveScheduleSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GeneratedSchedule is the effective schedule that is added to Cron
        /// </summary>
        [Input("generatedSchedule")]
        public Input<string>? GeneratedSchedule { get; set; }

        /// <summary>
        /// JobType defines to which job type this schedule applies
        /// </summary>
        [Input("jobType")]
        public Input<string>? JobType { get; set; }

        /// <summary>
        /// OriginalSchedule is the original user-defined schedule definition in the Schedule object.
        /// </summary>
        [Input("originalSchedule")]
        public Input<string>? OriginalSchedule { get; set; }

        [Input("scheduleRefs")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.K8up.V1.EffectiveScheduleSpecScheduleRefsArgs>? _scheduleRefs;

        /// <summary>
        /// ScheduleRefs holds a list of schedules for which the generated schedule applies to. The list may omit entries that aren't generated from smart schedules.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.K8up.V1.EffectiveScheduleSpecScheduleRefsArgs> ScheduleRefs
        {
            get => _scheduleRefs ?? (_scheduleRefs = new InputList<Pulumi.Kubernetes.Types.Inputs.K8up.V1.EffectiveScheduleSpecScheduleRefsArgs>());
            set => _scheduleRefs = value;
        }

        public EffectiveScheduleSpecArgs()
        {
        }
        public static new EffectiveScheduleSpecArgs Empty => new EffectiveScheduleSpecArgs();
    }
}
