// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    /// <summary>
    /// PodDNSConfigOption defines DNS resolver options of a pod.
    /// </summary>
    public class PreBackupPodSpecPodSpecDnsConfigOptionsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public PreBackupPodSpecPodSpecDnsConfigOptionsArgs()
        {
        }
        public static new PreBackupPodSpecPodSpecDnsConfigOptionsArgs Empty => new PreBackupPodSpecPodSpecDnsConfigOptionsArgs();
    }
}
