// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    /// <summary>
    /// PreBackupPodSpec define pods that will be launched during the backup. After the backup has finished (successfully or not), they should be removed again automatically by the operator.
    /// </summary>
    public class PreBackupPodSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// BackupCommand will be added to the backupcommand annotation on the pod.
        /// </summary>
        [Input("backupCommand")]
        public Input<string>? BackupCommand { get; set; }

        [Input("fileExtension")]
        public Input<string>? FileExtension { get; set; }

        /// <summary>
        /// Pod is a dummy struct to fix some code generation issues.
        /// </summary>
        [Input("pod")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.PreBackupPodSpecPodArgs>? Pod { get; set; }

        public PreBackupPodSpecArgs()
        {
        }
        public static new PreBackupPodSpecArgs Empty => new PreBackupPodSpecArgs();
    }
}
