// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    public class RestoreSpecBackendAzureArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("accountKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.RestoreSpecBackendAzureAccountKeySecretRefArgs>? AccountKeySecretRef { get; set; }

        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("accountNameSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.RestoreSpecBackendAzureAccountNameSecretRefArgs>? AccountNameSecretRef { get; set; }

        [Input("container")]
        public Input<string>? Container { get; set; }

        public RestoreSpecBackendAzureArgs()
        {
        }
        public static new RestoreSpecBackendAzureArgs Empty => new RestoreSpecBackendAzureArgs();
    }
}
