// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    public class RestoreSpecBackendS3Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("accessKeyIDSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.RestoreSpecBackendS3AccessKeyIDSecretRefArgs>? AccessKeyIDSecretRef { get; set; }

        [Input("bucket")]
        public Input<string>? Bucket { get; set; }

        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("secretAccessKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.RestoreSpecBackendS3SecretAccessKeySecretRefArgs>? SecretAccessKeySecretRef { get; set; }

        public RestoreSpecBackendS3Args()
        {
        }
        public static new RestoreSpecBackendS3Args Empty => new RestoreSpecBackendS3Args();
    }
}
