// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    /// <summary>
    /// Retention sets how many backups should be kept after a forget and prune
    /// </summary>
    public class ScheduleSpecPruneRetentionArgs : global::Pulumi.ResourceArgs
    {
        [Input("hostnames")]
        private InputList<string>? _hostnames;

        /// <summary>
        /// Hostnames is a filter on what hostnames the policy should be applied
        /// </summary>
        public InputList<string> Hostnames
        {
            get => _hostnames ?? (_hostnames = new InputList<string>());
            set => _hostnames = value;
        }

        [Input("keepDaily")]
        public Input<int>? KeepDaily { get; set; }

        [Input("keepHourly")]
        public Input<int>? KeepHourly { get; set; }

        [Input("keepLast")]
        public Input<int>? KeepLast { get; set; }

        [Input("keepMonthly")]
        public Input<int>? KeepMonthly { get; set; }

        [Input("keepTags")]
        private InputList<string>? _keepTags;
        public InputList<string> KeepTags
        {
            get => _keepTags ?? (_keepTags = new InputList<string>());
            set => _keepTags = value;
        }

        [Input("keepWeekly")]
        public Input<int>? KeepWeekly { get; set; }

        [Input("keepYearly")]
        public Input<int>? KeepYearly { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags is a filter on what tags the policy should be applied DO NOT CONFUSE THIS WITH KeepTags OR YOU'LL have a bad time
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ScheduleSpecPruneRetentionArgs()
        {
        }
        public static new ScheduleSpecPruneRetentionArgs Empty => new ScheduleSpecPruneRetentionArgs();
    }
}
