// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    public class ScheduleSpecRestoreBackendGcsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("accessTokenSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecRestoreBackendGcsAccessTokenSecretRefArgs>? AccessTokenSecretRef { get; set; }

        [Input("bucket")]
        public Input<string>? Bucket { get; set; }

        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        [Input("projectIDSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecRestoreBackendGcsProjectIDSecretRefArgs>? ProjectIDSecretRef { get; set; }

        public ScheduleSpecRestoreBackendGcsArgs()
        {
        }
        public static new ScheduleSpecRestoreBackendGcsArgs Empty => new ScheduleSpecRestoreBackendGcsArgs();
    }
}
