// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8up.V1
{

    /// <summary>
    /// ScheduleSpec defines the schedules for the various job types.
    /// </summary>
    public class ScheduleSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ArchiveSchedule manages schedules for the archival service
        /// </summary>
        [Input("archive")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecArchiveArgs>? Archive { get; set; }

        /// <summary>
        /// Backend allows configuring several backend implementations. It is expected that users only configure one storage type.
        /// </summary>
        [Input("backend")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecBackendArgs>? Backend { get; set; }

        /// <summary>
        /// BackupSchedule manages schedules for the backup service
        /// </summary>
        [Input("backup")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecBackupArgs>? Backup { get; set; }

        /// <summary>
        /// CheckSchedule manages the schedules for the checks
        /// </summary>
        [Input("check")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecCheckArgs>? Check { get; set; }

        /// <summary>
        /// FailedJobsHistoryLimit amount of failed jobs to keep for later analysis. KeepJobs is used property is not specified.
        /// </summary>
        [Input("failedJobsHistoryLimit")]
        public Input<int>? FailedJobsHistoryLimit { get; set; }

        /// <summary>
        /// KeepJobs amount of jobs to keep for later analysis. 
        ///  Deprecated: Use FailedJobsHistoryLimit and SuccessfulJobsHistoryLimit respectively.
        /// </summary>
        [Input("keepJobs")]
        public Input<int>? KeepJobs { get; set; }

        /// <summary>
        /// PodSecurityContext describes the security context with which actions (such as backups) shall be executed.
        /// </summary>
        [Input("podSecurityContext")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecPodSecurityContextArgs>? PodSecurityContext { get; set; }

        /// <summary>
        /// PruneSchedule manages the schedules for the prunes
        /// </summary>
        [Input("prune")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecPruneArgs>? Prune { get; set; }

        /// <summary>
        /// ResourceRequirementsTemplate describes the compute resource requirements (cpu, memory, etc.)
        /// </summary>
        [Input("resourceRequirementsTemplate")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecResourceRequirementsTemplateArgs>? ResourceRequirementsTemplate { get; set; }

        /// <summary>
        /// RestoreSchedule manages schedules for the restore service
        /// </summary>
        [Input("restore")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8up.V1.ScheduleSpecRestoreArgs>? Restore { get; set; }

        /// <summary>
        /// SuccessfulJobsHistoryLimit amount of successful jobs to keep for later analysis. KeepJobs is used property is not specified.
        /// </summary>
        [Input("successfulJobsHistoryLimit")]
        public Input<int>? SuccessfulJobsHistoryLimit { get; set; }

        public ScheduleSpecArgs()
        {
        }
        public static new ScheduleSpecArgs Empty => new ScheduleSpecArgs();
    }
}
