---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - pv-movies.yaml
  - pvc-movies.yaml
  - pv-tv.yaml
  - pvc-tv.yaml
  - jellyfin.yaml
  - ingress.yaml
#  - restic-credentials.sops.yaml
#  - backup.yaml