---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-movies
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: 78181a1a-c4b1-4f92-979b-949aba92eea1
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/movies
      node_attach_driver: nfs
      provisioner_driver: node-manual
