---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-tv
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: efa2c23e-6b93-4c9d-b068-ccb9a5bf3411
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/tv
      node_attach_driver: nfs
      provisioner_driver: node-manual
