---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-movies
spec:
  storageClassName: ""
  volumeName: pv-jellyfin-movies
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti

