---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-tv
spec:
  storageClassName: ""
  volumeName: pv-jellyfin-tv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti

