---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts/
    targetRevision: 25.0.0
    helm:
      releaseName: traefik
      valuesObject:
        service:
          annotations:
            "io.cilium/lb-ipam-ips": "172.16.61.1"
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
          kubernetesCRD:
            allowExternalNameServices: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik

