---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 15m
  values:
    service:
      annotations:
        "io.cilium/lb-ipam-ips": "172.16.61.1"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
