---
apiVersion: v1
kind: Service
metadata:
  name: broadcast-box
  labels:
    app: broadcast-box
spec:
  selector:
    app: broadcast-box
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: web
    - name: data
      port: 8080
      protocol: UDP
      targetPort: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-box
  labels:
    app: broadcast-box
spec:
  selector:
    matchLabels:
      app: broadcast-box
  replicas: 1
  template:
    metadata:
      labels:
        app: broadcast-box
    spec:
      hostNetwork: true
      containers:
      - name: broadcast-box
        image: seaduboi/broadcast-box
        env:
          - name: INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP
            value: "yes"
          - name: STUN_SERVERS
            value: "stun.l.google.com:19302|stun1.l.google.com:19302"
        ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          - containerPort: 8080
            name: data
            protocol: UDP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
