---
apiVersion: v1
kind: Service
metadata:
  name: broadcast-box
  labels:
    app: broadcast-box
spec:
  selector:
    app: broadcast-box
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: web
    - name: data
      port: 3478
      protocol: UDP
      targetPort: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-box
  labels:
    app: broadcast-box
spec:
  selector:
    matchLabels:
      app: broadcast-box
  replicas: 1
  template:
    metadata:
      labels:
        app: broadcast-box
    spec:
      containers:
      - name: broadcast-box
        image: seaduboi/broadcast-box
        env:
          - name: NAT_1_TO_1_IP
            value: "172.16.61.4"
          - name: UDP_MUX_PORT
            value: "3478"
          - name: NETWORK_TEST_ON_START
            value: "false"
        ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          - containerPort: 3478
            name: data
            protocol: UDP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
