---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/infrastructure/kube-prometheus"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
