---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-controller
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/infrastructure/traefik/controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traefik
      namespace: traefik
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-controller
  interval: 5m
  path: "./kubernetes/infrastructure/traefik/policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system