---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: infisical-auth
spec:
  infisicalConnectionRef:
    name: infisical-connection
    namespace: infisical-operator-system
  method: universal
  universal:
    clientIdRef:
      name: infisical-credentials
      namespace: copyparty
      key: clientId
    clientSecretRef:
      name: infisical-credentials
      namespace: copyparty
      key: clientSecret
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-copyparty-config
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: copyparty
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: copyparty-tm-ep
      environmentSlug: dev
      secretPath: /copyparty
  targets: []
