---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-copyparty-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi

