---
apiVersion: v1
kind: Service
metadata:
  name: copyparty
  labels:
    app: copyparty
spec:
  selector:
    app: copyparty
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

