---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

resources:
  - ../../base
  - paperless.yaml
  - redis.yaml
  - ingress.yaml
  - restic-credentials.sealed.yaml
  - backup.yaml

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.8.6
