---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - paperless.yaml
  - redis.yaml
  - ingress.yaml
#  - restic-credentials.sops.yaml
#  - backup.yaml