---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  labels:
    app: paperless
spec:
  selector:
    app: paperless
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: web-ui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paperless
  labels:
    app: paperless
spec:
  selector:
    matchLabels:
      app: paperless
  serviceName: paperless
  replicas: 1
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:2.6.3
        env:
          - name: USERMAP_UID
            value: "1001"
          - name: USERMAP_GID
            value: "1001"
          - name: PAPERLESS_URL
            value: "https://paperless.internal.paulfriedrich.me"
          - name: PAPERLESS_PORT
            value: "8000"
          - name: PAPERLESS_REDIS
            value: "redis://redis.paperless.svc.cluster.local:6379"
          - name: PAPERLESS_OCR_LANGUAGE
            value: "deu"
          - name: PAPERLESS_TIME_ZONE
            value: "Europe/Berlin"
        ports:
          - containerPort: 8000
            name: web-ui
            protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /usr/src/paperless/data
            subPath: data
          - name: data
            mountPath: /usr/src/paperless/media
            subPath: media
          - name: data
            mountPath: /usr/src/paperless/export
            subPath: export
          - name: data
            mountPath: /usr/src/paperless/consume
            subPath: consume
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: paperless
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "freenas-api-iscsi-csi"
      resources:
        requests:
          storage: 32Gi
