---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restic-credentials
  namespace: paperless
spec:
  encryptedData:
    RESTIC_PASSWORD: AgAn7rhG4+8/YFvPYr1oz7CGzfd2fUJ88pf8KZp+GxX9yC7ec4fImQayWCwqpJECT3F/lu8PtZH9wgGqOD0YFNpELbL/vOH3UuWf9OM9yVdKyh7lhlSpPCZb6p9SgZPam2jNCpHCX7bnHf/kZFPQqAfWCZYw91AlfVCkBK+yH1BB2iEh7fxXRAvKTuVPoBXupSZVF5ywZUsnzxLbcaIns132tuas13SnpAEQVfIAdZq3NFO3e44im7coMdWo/04Xk/FNqXvopfO7CDoj5dZtkmrlBQid7ywUtXW/ipUYwWKDDaa5020XipUuIZnM1V8jEKoe8ONdJ0mbZiVRbIfNjLK/mEEQBQ3qUDth6HjDJovSlKxCLaKFG/A12vdQ6oF4mWqrod/frdcxqhvEnW8afvg2rh6hJPnZmV5XjsUhVQ4z0fI6dE3TIiDL4lmgbnYBU5FUTgEOvIi+evZH+HeNY8yxKuOgqqVncZX5DHLfdivECBX47emAkCJ87rWGzqfXh7Qdu3eGO2/vITp54QbOJsju3+MF/yivi9oiiMMRX1YrzJsYWLX1JLIuY5jyr+8qagNUDoo49BJVMJHpdcG+3fJ1gv/aHbXJS0OHSpbbDyBWpAuKMfAl+EO/fg4v8h2sK1Wyei1zdJ9X8SuF9QjBF/ExYGFbAdHp6gnkQUnaOT4BWAoRrXtRIfF7r7bhNraG3mJKX1sUiqHkGbZ6hlv++PgVCnFTTrrkjOEZ
    RESTIC_REPOSITORY: AgBhl4NS7VUsQ8lDcK/cNBHSTG7JCNThn6qnDZjh/GBaWJmjAsT0mPVd9Adau3mhIDwV1GUOQgjuNNYxTbdf3DoR0oZq65oOK1BiJE+EPxaeFc2mOClVbKfbjb1Fczfi5RK4fsSwS1zSPaXk3dVMgFQvuG/NhPhbHdfP4pC0y3Tk+ZF4BH5/IcN4V+li9p50QXO0M9QaFwGhD4vjUMTlI8PBHt2L5UuGLUAJ4Bmz7oziySFZKKxofdlKEXoMsZ4bHMOfe2cjbMVcGYMBLrCc2pia+LyDWsIHYAQcaR/0iWXsMADPYT1O7ZVLsXTOMC6EsD8XMAqtCIVWV6XiPt1dykgAl8JQT1pWtagSwIjUSPNQ+pE1UrYDTiMC0gx1kFW18SfYqwhk9kIkUqCFnSZ4B1Al1XiYucLDmaVdQ/Raft1t5dEWxyUDr/PJLV1F8EgQOHwHo4AgEQwSu0iusMByXaBXF4WtlybTA6UoU0MnD5CthzcnnU9feSV8NZf2HUfc2rcKkK5dhK+lOmXTaVle+8BhGZb3jObIlRL+vHYTxp5TMEU8rgxPA0Nn0ThrrH/7Tno4iTLvzNgUkYycJHlTn1/OssFNzPB+w9HVa0Tu1LTBtyOl9vJZb6ztPHQ5Q90638+OkWAwfhPMqhZtk6p/ENoZkm8fPD1JjD/51kh5RuG9O5gTvL7sw+AQwgiLuAx7DTRLVNajJGeUiL4Gpv6iCAZ5m4SOYBdMZJFoFhMkvl3NfbaF/oRBexrJeN9snIL+px0LaxqmKbUT3nXc1DhB9FKzYA==
  template:
    metadata:
      creationTimestamp: null
      name: restic-credentials
      namespace: paperless
    type: Opaque
