// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Piraeus.V1
{

    [OutputType]
    public sealed class LinstorSatelliteSpecStoragePools
    {
        /// <summary>
        /// Configures a file system based storage pool, allocating a regular file per volume.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsFilePool FilePool;
        /// <summary>
        /// Configures a file system based storage pool, allocating a sparse file per volume.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsFileThinPool FileThinPool;
        /// <summary>
        /// Configures a LVM Volume Group as storage pool.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsLvmPool LvmPool;
        /// <summary>
        /// Configures a LVM Thin Pool as storage pool.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsLvmThinPool LvmThinPool;
        /// <summary>
        /// Name of the storage pool in linstor.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Properties to set on the storage pool.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsProperties> Properties;
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsSource Source;

        [OutputConstructor]
        private LinstorSatelliteSpecStoragePools(
            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsFilePool filePool,

            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsFileThinPool fileThinPool,

            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsLvmPool lvmPool,

            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsLvmThinPool lvmThinPool,

            string name,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsProperties> properties,

            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsSource source)
        {
            FilePool = filePool;
            FileThinPool = fileThinPool;
            LvmPool = lvmPool;
            LvmThinPool = lvmThinPool;
            Name = name;
            Properties = properties;
            Source = source;
        }
    }
}
