// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Piraeus.V1
{

    /// <summary>
    /// LinstorNodeConnectionSpec defines the desired state of LinstorNodeConnection
    /// </summary>
    [OutputType]
    public sealed class LinstorNodeConnectionSpec
    {
        /// <summary>
        /// Paths configure the network path used when connecting two nodes.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorNodeConnectionSpecPaths> Paths;
        /// <summary>
        /// Properties to apply for the node connection. 
        ///  Use to create default settings for DRBD that should apply to all resources connections between a set of cluster nodes.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorNodeConnectionSpecProperties> Properties;
        /// <summary>
        /// Selector selects which pair of Satellites the connection should apply to. If not given, the connection will be applied to all connections.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorNodeConnectionSpecSelector> Selector;

        [OutputConstructor]
        private LinstorNodeConnectionSpec(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorNodeConnectionSpecPaths> paths,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorNodeConnectionSpecProperties> properties,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorNodeConnectionSpecSelector> selector)
        {
            Paths = paths;
            Properties = properties;
            Selector = selector;
        }
    }
}
