// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Piraeus.V1
{

    /// <summary>
    /// Patch represent either a Strategic Merge Patch or a JSON patch and its targets.
    /// </summary>
    [OutputType]
    public sealed class LinstorSatelliteSpecPatches
    {
        /// <summary>
        /// Options is a list of options for the patch
        /// </summary>
        public readonly ImmutableDictionary<string, bool> Options;
        /// <summary>
        /// Patch is the content of a patch.
        /// </summary>
        public readonly string Patch;
        /// <summary>
        /// Target points to the resources that the patch is applied to
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecPatchesTarget Target;

        [OutputConstructor]
        private LinstorSatelliteSpecPatches(
            ImmutableDictionary<string, bool> options,

            string patch,

            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecPatchesTarget target)
        {
            Options = options;
            Patch = patch;
            Target = target;
        }
    }
}
