// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Piraeus.V1
{

    /// <summary>
    /// LinstorSatelliteSpec defines the desired state of LinstorSatellite
    /// </summary>
    [OutputType]
    public sealed class LinstorSatelliteSpec
    {
        /// <summary>
        /// ClusterRef references the LinstorCluster used to create this LinstorSatellite.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecClusterRef ClusterRef;
        /// <summary>
        /// InternalTLS configures secure communication for the LINSTOR Satellite. 
        ///  If set, the control traffic between LINSTOR Controller and Satellite will be encrypted using mTLS. The Controller will use the client key from `LinstorCluster.spec.internalTLS` when connecting.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecInternalTLS InternalTLS;
        /// <summary>
        /// Patches is a list of kustomize patches to apply. 
        ///  See https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/ for how to create patches.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecPatches> Patches;
        /// <summary>
        /// Properties is a list of properties to set on the node.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecProperties> Properties;
        /// <summary>
        /// Repository used to pull workload images.
        /// </summary>
        public readonly string Repository;
        /// <summary>
        /// StoragePools is a list of storage pools to configure on the node.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePools> StoragePools;

        [OutputConstructor]
        private LinstorSatelliteSpec(
            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecClusterRef clusterRef,

            Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecInternalTLS internalTLS,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecPatches> patches,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecProperties> properties,

            string repository,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Piraeus.V1.LinstorSatelliteSpecStoragePools> storagePools)
        {
            ClusterRef = clusterRef;
            InternalTLS = internalTLS;
            Patches = patches;
            Properties = properties;
            Repository = repository;
            StoragePools = storagePools;
        }
    }
}
