// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Piraeus.V1
{

    /// <summary>
    /// ExternalController references an external controller. When set, the Operator will skip deploying a LINSTOR Controller and instead use the external cluster to register satellites.
    /// </summary>
    [OutputType]
    public sealed class LinstorClusterSpecExternalController
    {
        /// <summary>
        /// URL of the external controller.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private LinstorClusterSpecExternalController(string url)
        {
            Url = url;
        }
    }
}
