// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Piraeus.V1
{

    [OutputType]
    public sealed class LinstorClusterSpecProperties
    {
        /// <summary>
        /// Name of the property to set.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Value to set the property to.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private LinstorClusterSpecProperties(
            string name,

            string value)
        {
            Name = name;
            Value = value;
        }
    }
}
