k8s-monitoring:
  cluster:
    name: internal-paulfriedrich-me-prod

  destinations:
    prometheus:
      type: prometheus
      url: http://monitoring.internal.paulfriedrich.me:9090/api/v1/write
    loki:
      type: loki
      url: http://monitoring.internal.paulfriedrich.me:3100/loki/api/v1/push

  collectors:
    alloy-metrics:
      presets: [small, clustered, statefulset]
    alloy-logs:
      presets: [small, filesystem-log-reader, daemonset]
    alloy-singleton:
      presets: [small, deployment]

  clusterMetrics:
    enabled: true
    collector: alloy-metrics
    controlPlane:
      enabled: true
    kubeProxy:
      enabled: false

  hostMetrics:
    enabled: true
    collector: alloy-metrics
    linuxHosts:
      enabled: true

  clusterEvents:
    enabled: true
    collector: alloy-singleton

  podLogsViaLoki:
    enabled: true
    collector: alloy-logs

  annotationAutodiscovery:
    enabled: true
    collector: alloy-metrics

  telemetryServices:
    kube-state-metrics:
      deploy: true
    node-exporter:
      deploy: true

  selfReporting:
    enabled: false
