- op: add
  path: /machine/install/extensions
  value:
    - image: ghcr.io/siderolabs/drbd:9.2.2-v1.4.5
- op: add
  path: /machine/kernel
  value:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
