---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/infrastructure/volsync"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
