---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: backube-charts
        namespace: flux-system
      interval: 30m
