---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-movies
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: 78181a1a-c4b1-4f92-979b-949aba92eea1
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/movies
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-movies
spec:
  storageClassName: ""
  volumeName: pv-jellyfin-movies
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-tv
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: efa2c23e-6b93-4c9d-b068-ccb9a5bf3411
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/tv
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-tv
spec:
  storageClassName: ""
  volumeName: pv-jellyfin-tv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
