---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@git.sr.ht:~pfriedrich/home-ops'
    path: kubernetes/infrastructure/sealed-secrets
    targetRevision: HEAD
    kustomize:
      nameSuffix: '-wutekt'
      namespace: sealed-secrets
  destination:
    server: 'https://kubernetes.default.svc'
