clusterName: internal-paulfriedrich-me-prod
talosVersion: v1.12.9
kubernetesVersion: v1.34.2
endpoint: https://kube.internal.paulfriedrich.me:6443
nodes:
  - hostname: talos-control-eex0
    ipAddress: 10.0.60.20
    installDisk: /dev/vda
    controlPlane: true
    nameservers:
      - 10.0.60.1
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:98:03:14
        dhcp: false
        addresses:
          - 10.0.60.20/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.60.1
        vip:
          ip: 10.0.60.5
    machineSpec:
      secureboot: true
      useUKI: true
    patches:
      - "@./patches/logging-control-eex0.yaml"
  - hostname: talos-control-vrcn
    ipAddress: 10.0.60.21
    installDisk: /dev/vda
    controlPlane: true
    nameservers:
      - 10.0.60.1
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:ad:12:af
        dhcp: false
        addresses:
          - 10.0.60.21/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.60.1
        vip:
          ip: 10.0.60.5
    machineSpec:
      secureboot: true
      useUKI: true
    patches:
      - "@./patches/logging-control-vrcn.yaml"
  - hostname: talos-control-euvu
    ipAddress: 10.0.60.22
    installDisk: /dev/vda
    controlPlane: true
    nameservers:
      - 10.0.60.1
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:6a:02:33
        dhcp: false
        addresses:
          - 10.0.60.22/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.60.1
        vip:
          ip: 10.0.60.5
    machineSpec:
      secureboot: true
      useUKI: true
    patches:
      - "@./patches/logging-control-euvu.yaml"
  - hostname: talos-worker-74s1
    ipAddress: 10.0.60.23
    installDisk: /dev/vda
    controlPlane: false
    nameservers:
      - 10.0.60.1
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:66:d6:87
        dhcp: false
        addresses:
          - 10.0.60.23/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.60.1
    machineSpec:
      secureboot: true
      useUKI: true
    patches:
      - "@./patches/longhorn-worker-74s1.yaml"
      - "@./patches/logging-worker-74s1.yaml"
  - hostname: talos-worker-8up6
    ipAddress: 10.0.60.24
    installDisk: /dev/vda
    controlPlane: false
    nameservers:
      - 10.0.60.1
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:1f:17:b6
        dhcp: false
        addresses:
          - 10.0.60.24/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.60.1
    machineSpec:
      secureboot: true
      useUKI: true
    patches:
      - "@./patches/longhorn-worker-8up6.yaml"
      - "@./patches/logging-worker-8up6.yaml"
  - hostname: talos-worker-lyfg
    ipAddress: 10.0.60.25
    installDisk: /dev/vda
    controlPlane: false
    nameservers:
      - 10.0.60.1
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:5a:01:4f
        dhcp: false
        addresses:
          - 10.0.60.25/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.60.1
    machineSpec:
      secureboot: true
      useUKI: true
    patches:
      - "@./patches/longhorn-worker-lyfg.yaml"
      - "@./patches/logging-worker-lyfg.yaml"
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - talos.logging.kernel=tcp://10.0.60.19:6050/
  imageSchematic:
    customization:
      extraKernelArgs:
        - talos.logging.kernel=tcp://10.0.60.19:6050/
  patches:
    - "@./patches/install-cilium-controlplane.yaml"
    - "@./patches/scheduler-config.yaml"
    - "@./patches/controller-manager-config.yaml"
    - "@./patches/dns-config.yaml"
worker:
  schematic:
    customization:
      extraKernelArgs:
        - talos.logging.kernel=tcp://10.0.60.19:6050/
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
  imageSchematic:
    customization:
      extraKernelArgs:
        - talos.logging.kernel=tcp://10.0.60.19:6050/
  patches:
    - "@./patches/install-cilium-worker.yaml"
    - "@./patches/enable-peering.yaml"
    - "@./patches/dns-config.yaml"
    - "@./patches/enable-user-namespaces.yaml"
    - "@./patches/longhorn-common.yaml"
