---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/infrastructure/democratic-csi/drivers"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi-snapshot-controller
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/infrastructure/democratic-csi/snapshot-controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
