dcsi-fn-api-iscsi:
    storageClasses:
        - name: ENC[AES256_GCM,data:f1ev1e0KfrEPZKMObCNw/C7Gulk9,iv:YT6sCwH0Z4ZSOSyUZbICFW3sQdQ6AoGVvG8o/MF/ugY=,tag:Mf0iMZ5KL8T5Q2a/3fE6PQ==,type:str]
          secrets:
            node-stage-secret:
                node-db.node.session.auth.authmethod: ENC[AES256_GCM,data:sAHj+A==,iv:5Gicd/ZtY6Vmhwua/Ug/Oao64iLP9npOCi0PW626x+w=,tag:cP/SrpW7+J3ZUwYYEwz5mQ==,type:str]
                node-db.node.session.auth.username: ENC[AES256_GCM,data:JL8t2/IZjht1,iv:G0MjZCv/dNDkuy+v11z/8wVU2uwJO6rHZPbkyniHHiM=,tag:PiIc6KTlQgz0fccIxedF0A==,type:str]
                node-db.node.session.auth.password: ENC[AES256_GCM,data:dodoSWAwLZq3aRDKLWc3Rw==,iv:MnTCaPKIyeekXVt0XgJQi1JvrthReEWtaimQQnmXqJw=,tag:OZ8FA4P8esLz0KGNhMr4wQ==,type:str]
                node-db.node.session.auth.username_in: ENC[AES256_GCM,data:oymuOVKtgVv6,iv:jlKYGypwlPs2XwMm0zhWdDuBZgW7TfUG019rBy9WiNM=,tag:DelJLF2/7xCyIkcRlq00bw==,type:str]
                node-db.node.session.auth.password_in: ENC[AES256_GCM,data:bVqhLqFntRrSs00o/njm8A==,iv:VakR5ij8UgBQja0TkO9N2PAF1RI2OiFwqiPnDJHGx/o=,tag:5x63XO8SaxSAQmmINAEnXA==,type:str]
    driver:
        config:
            httpConnection:
                apiKey: ENC[AES256_GCM,data:ZPOkcFDmR/G4IlZ/GeM92poen54W5s1Y6Gg602gzo0M0zCd5w/rLHdq5W41zNNzc/Pojn2Z2/9peKgIRcMWdslva,iv:M8pRUvjSUrGYzZio7GCMPsZ/qYr+rsxcM09o1H4h4Q8=,tag:L9HaYFQUpv82UkhjDORLsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxmmkdzm0gas4z03q6mnzcv5exs7wlxjxrp8qzh0eujzqk8wvvyqk3qcjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAramxZZmk2RG53Nk5CM1kx
            b25xaFcvVWNDODI3Z1hnamp0QzlRd0d5c2prCkhxdzE4ek43Q3VxV1VaVUI1SWNF
            cGZWVVNSZ3Q2SHFCc0tDZ3N5OEw4eFEKLS0tIFc1ZnBEN1FtSU5LKzY3eVVkU1Rw
            ekVuaU1FL2JxMm5vNUpLNGc5K0o0VUUK6Rid4Q3bUoJ/2jm/rjaaCX5nJPYE/7bg
            1hhfZdQKaRqZN//6P5DXHOkI/N7NQjxvZZp1O11DP2RX+uBspSJjZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spf8ku8hn2yc6g7v3tlh8859chmxkv952lr52ppwknzwl7eh58sq9yu56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFblJyeGFQZ1ZONllqSnY5
            NVVBSHZQdHV6SE9qSWRLWjV2ZVdqaWtBTlRVCmVzMXVGa1o3Z01hc1JIbU1RQXpD
            bk9DYXV3M05KdnRlMVptTDBOa0Q1UlUKLS0tIG0vYUd4WEtLV3c2Q1NtME1scHox
            NzZNUkd2ZXAwMnBxZ3RKV1AzTWxYd28KQ1akKhHQUJwfrXL0QRo8xTLhq8XM2nQr
            6pqUp2FX2chPSMdFLRZo/hKsVFaG4p6UMZS0awZqtqERhg/I9tgkkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T18:05:16Z"
    mac: ENC[AES256_GCM,data:24NvoFka8fYD5/DAmah9doLtMufwU0IF/C+V+r06dL/T90ltNmRfVUY/xFUw6UM7k4A5PiYLJ/I80gwgM0BOgp+4x8XwY43ShX/qsDEp1Z26JVUNW1uxkFgKlKLZCXKD9SQv4VKvcLqKRkDWZK12evO2XoVWJ9YyK8Pm6fY/QkU=,iv:384dEj0aissThzOMlw+GR44lt1BeyPHQL9XB6qJRJ1A=,tag:GzVSpUjEJiNGFV/3IMkGbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
