---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/clusters/home-argo
    repoURL: https://git.sr.ht/~pfriedrich/home-ops
    targetRevision: HEAD
