---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
spec:
  project: default
  source:
    path: kubernetes/infrastructure/root
    repoURL: https://git.sr.ht/~pfriedrich/home-ops
    targetRevision: HEAD
    helm:
      values: |
        spec:
          source:
            repoURL: https://git.sr.ht/~pfriedrich/home-ops
            targetRevision: HEAD
          destination:
            server: https://kubernetes.default.svc
  destination:
    namespace: default
    server: https://kubernetes.default.svc
