---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
  - git:
      repoURL: {{ .Values.spec.source.repoURL }}
      revision: {{ .Values.spec.source.targetRevision }}
      files:
        - path: kubernetes/infrastructure/**/config.json
  template:
    metadata:
      name: '{{ `{{ .name }}` }}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        path: '{{ `{{ .path.path }}` }}'
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: '{{ `{{ .namespace }}` }}'
  templatePatch: |
    spec:
      syncPolicy:
        syncOptions:
          {{`{{- range $value := .syncPolicy.syncOptions }}
          - {{ $value }}
          {{- end }}`}}
        managedNamespaceMetadata:
          labels:
            {{`{{- range $value := .syncPolicy.managedNamespaceMetadata.labels }}
              {{ $value }}
            {{- end }}`}}
            
