// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Piraeus.V1
{

    /// <summary>
    /// CertManager references a cert-manager Issuer or ClusterIssuer. If set, a Certificate resource will be created, provisioning the secret references in SecretName using the issuer configured here.
    /// </summary>
    public class LinstorClusterSpecInternalTLSCertManagerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group of the resource being referred to.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        /// <summary>
        /// Kind of the resource being referred to.
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// Name of the resource being referred to.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public LinstorClusterSpecInternalTLSCertManagerArgs()
        {
        }
        public static new LinstorClusterSpecInternalTLSCertManagerArgs Empty => new LinstorClusterSpecInternalTLSCertManagerArgs();
    }
}
