// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Piraeus.V1
{

    /// <summary>
    /// LinstorSatelliteSpec defines the desired state of LinstorSatellite
    /// </summary>
    public class LinstorSatelliteSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ClusterRef references the LinstorCluster used to create this LinstorSatellite.
        /// </summary>
        [Input("clusterRef", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecClusterRefArgs> ClusterRef { get; set; } = null!;

        /// <summary>
        /// InternalTLS configures secure communication for the LINSTOR Satellite. 
        ///  If set, the control traffic between LINSTOR Controller and Satellite will be encrypted using mTLS. The Controller will use the client key from `LinstorCluster.spec.internalTLS` when connecting.
        /// </summary>
        [Input("internalTLS")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecInternalTLSArgs>? InternalTLS { get; set; }

        [Input("patches")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecPatchesArgs>? _patches;

        /// <summary>
        /// Patches is a list of kustomize patches to apply. 
        ///  See https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/ for how to create patches.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecPatchesArgs> Patches
        {
            get => _patches ?? (_patches = new InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecPatchesArgs>());
            set => _patches = value;
        }

        [Input("properties")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecPropertiesArgs>? _properties;

        /// <summary>
        /// Properties is a list of properties to set on the node.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecPropertiesArgs> Properties
        {
            get => _properties ?? (_properties = new InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecPropertiesArgs>());
            set => _properties = value;
        }

        /// <summary>
        /// Repository used to pull workload images.
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        [Input("storagePools")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsArgs>? _storagePools;

        /// <summary>
        /// StoragePools is a list of storage pools to configure on the node.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsArgs> StoragePools
        {
            get => _storagePools ?? (_storagePools = new InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteSpecStoragePoolsArgs>());
            set => _storagePools = value;
        }

        public LinstorSatelliteSpecArgs()
        {
        }
        public static new LinstorSatelliteSpecArgs Empty => new LinstorSatelliteSpecArgs();
    }
}
