// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Piraeus.V1
{

    public class LinstorNodeConnectionSpecPropertiesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the property to set.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Value to set the property to.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public LinstorNodeConnectionSpecPropertiesArgs()
        {
        }
        public static new LinstorNodeConnectionSpecPropertiesArgs Empty => new LinstorNodeConnectionSpecPropertiesArgs();
    }
}
