// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Piraeus.V1
{

    public class LinstorSatelliteConfigurationSpecStoragePoolsSourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("hostDevices")]
        private InputList<string>? _hostDevices;

        /// <summary>
        /// HostDevices is a list of device paths used to configure the given pool.
        /// </summary>
        public InputList<string> HostDevices
        {
            get => _hostDevices ?? (_hostDevices = new InputList<string>());
            set => _hostDevices = value;
        }

        public LinstorSatelliteConfigurationSpecStoragePoolsSourceArgs()
        {
        }
        public static new LinstorSatelliteConfigurationSpecStoragePoolsSourceArgs Empty => new LinstorSatelliteConfigurationSpecStoragePoolsSourceArgs();
    }
}
