// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Piraeus.V1
{

    /// <summary>
    /// Configures a LVM Thin Pool as storage pool.
    /// </summary>
    public class LinstorSatelliteSpecStoragePoolsLvmThinPoolArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ThinPool is the name of the thinpool LV (without VG prefix).
        /// </summary>
        [Input("thinPool")]
        public Input<string>? ThinPool { get; set; }

        [Input("volumeGroup")]
        public Input<string>? VolumeGroup { get; set; }

        public LinstorSatelliteSpecStoragePoolsLvmThinPoolArgs()
        {
        }
        public static new LinstorSatelliteSpecStoragePoolsLvmThinPoolArgs Empty => new LinstorSatelliteSpecStoragePoolsLvmThinPoolArgs();
    }
}
