// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Piraeus.V1
{

    /// <summary>
    /// LinstorSatelliteConfigurationSpec defines a partial, desired state of a LinstorSatelliteSpec. 
    ///  All the LinstorSatelliteConfiguration resources with matching NodeSelector will be merged into a single LinstorSatelliteSpec.
    /// </summary>
    public class LinstorSatelliteConfigurationSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// InternalTLS configures secure communication for the LINSTOR Satellite. 
        ///  If set, the control traffic between LINSTOR Controller and Satellite will be encrypted using mTLS.
        /// </summary>
        [Input("internalTLS")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecInternalTLSArgs>? InternalTLS { get; set; }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;

        /// <summary>
        /// NodeSelector selects which LinstorSatellite resources this spec should be applied to. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
        /// </summary>
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("patches")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecPatchesArgs>? _patches;

        /// <summary>
        /// Patches is a list of kustomize patches to apply. 
        ///  See https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/ for how to create patches.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecPatchesArgs> Patches
        {
            get => _patches ?? (_patches = new InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecPatchesArgs>());
            set => _patches = value;
        }

        [Input("properties")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecPropertiesArgs>? _properties;

        /// <summary>
        /// Properties is a list of properties to set on the node.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecPropertiesArgs> Properties
        {
            get => _properties ?? (_properties = new InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecPropertiesArgs>());
            set => _properties = value;
        }

        [Input("storagePools")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecStoragePoolsArgs>? _storagePools;

        /// <summary>
        /// StoragePools is a list of storage pools to configure on the node.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecStoragePoolsArgs> StoragePools
        {
            get => _storagePools ?? (_storagePools = new InputList<Pulumi.Kubernetes.Types.Inputs.Piraeus.V1.LinstorSatelliteConfigurationSpecStoragePoolsArgs>());
            set => _storagePools = value;
        }

        public LinstorSatelliteConfigurationSpecArgs()
        {
        }
        public static new LinstorSatelliteConfigurationSpecArgs Empty => new LinstorSatelliteConfigurationSpecArgs();
    }
}
