// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Piraeus.V1
{

    /// <summary>
    /// Configures a file system based storage pool, allocating a regular file per volume.
    /// </summary>
    public class LinstorSatelliteConfigurationSpecStoragePoolsFilePoolArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Directory is the path to the host directory used to store volume data.
        /// </summary>
        [Input("directory")]
        public Input<string>? Directory { get; set; }

        public LinstorSatelliteConfigurationSpecStoragePoolsFilePoolArgs()
        {
        }
        public static new LinstorSatelliteConfigurationSpecStoragePoolsFilePoolArgs Empty => new LinstorSatelliteConfigurationSpecStoragePoolsFilePoolArgs();
    }
}
