apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-stunner-config
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: livekit
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: livekit-poi3
      environmentSlug: dev
      secretPath: /stunner
  targets:
    - name: stunner-secrets
      namespace: livekit
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          type: static
          username: "{{ `{{ .STUNNER_USERNAME.Value }}` }}"
          password: "{{ `{{ .STUNNER_PASSWORD.Value }}` }}"
