---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vyos
resources:
  - ../../base
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml
  - pipeline.yaml

patches:
  - path: namespace.yaml
