---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: vyos-build
spec:
  description: Builds a VyOS iso
  params:
    - name: repo-url
      type: string
      description: URL of the git repo
    - name: revision
      type: string
      description: Revision to clone from the git repo
  workspaces:
    - name: shared-data
      description: Cloned repository
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build
      runAfter: [ "fetch-source" ]
      taskRef:
        name: build-image
      workspaces:
        - name: source
          workspace: shared-data
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  description: Builds a VyOS image.
  workspaces:
    - name: source
  steps:
    - name: build-vyos-image
      image: vyos/vyos-build:current
      securityContext:
        runAsUser: 0
        privileged: true
      script: | 
        #!/usr/bin/env sh
        cd $(workspaces.source.path)
        make clean
        ./build-vyos-image generic --architecture amd64 --build-by "vyos@mail.paulfriedrich.me"
