// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    /// <summary>
    /// ScheduleRef represents a reference to a Schedule resource
    /// </summary>
    [OutputType]
    public sealed class EffectiveScheduleSpecScheduleRefs
    {
        public readonly string Name;
        public readonly string Namespace;

        [OutputConstructor]
        private EffectiveScheduleSpecScheduleRefs(
            string name,

            string @namespace)
        {
            Name = name;
            Namespace = @namespace;
        }
    }
}
