// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    /// <summary>
    /// Projection that may be projected along with other supported volume types
    /// </summary>
    [OutputType]
    public sealed class PreBackupPodSpecPodSpecVolumesProjectedSources
    {
        /// <summary>
        /// configMap information about the configMap data to project
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesConfigMap ConfigMap;
        /// <summary>
        /// downwardAPI information about the downwardAPI data to project
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesDownwardAPI DownwardAPI;
        /// <summary>
        /// secret information about the secret data to project
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesSecret Secret;
        /// <summary>
        /// serviceAccountToken is information about the serviceAccountToken data to project
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesServiceAccountToken ServiceAccountToken;

        [OutputConstructor]
        private PreBackupPodSpecPodSpecVolumesProjectedSources(
            Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesConfigMap configMap,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesDownwardAPI downwardAPI,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesSecret secret,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.PreBackupPodSpecPodSpecVolumesProjectedSourcesServiceAccountToken serviceAccountToken)
        {
            ConfigMap = configMap;
            DownwardAPI = downwardAPI;
            Secret = secret;
            ServiceAccountToken = serviceAccountToken;
        }
    }
}
