// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    /// <summary>
    /// Status defines the observed state of a generic K8up job. It is used for the operator to determine what to do.
    /// </summary>
    [OutputType]
    public sealed class RestoreStatus
    {
        /// <summary>
        /// Conditions provide a standard mechanism for higher-level status reporting from a controller. They are an extension mechanism which allows tools and other controllers to collect summary information about resources without needing to understand resource-specific status details.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.RestoreStatusConditions> Conditions;
        public readonly bool Exclusive;
        public readonly bool Finished;
        public readonly bool Started;

        [OutputConstructor]
        private RestoreStatus(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.RestoreStatusConditions> conditions,

            bool exclusive,

            bool finished,

            bool started)
        {
            Conditions = conditions;
            Exclusive = exclusive;
            Finished = finished;
            Started = started;
        }
    }
}
