// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    [OutputType]
    public sealed class ScheduleSpecBackendGcs
    {
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendGcsAccessTokenSecretRef AccessTokenSecretRef;
        public readonly string Bucket;
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendGcsProjectIDSecretRef ProjectIDSecretRef;

        [OutputConstructor]
        private ScheduleSpecBackendGcs(
            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendGcsAccessTokenSecretRef accessTokenSecretRef,

            string bucket,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendGcsProjectIDSecretRef projectIDSecretRef)
        {
            AccessTokenSecretRef = accessTokenSecretRef;
            Bucket = bucket;
            ProjectIDSecretRef = projectIDSecretRef;
        }
    }
}
