// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    /// <summary>
    /// RestoreMethod contains how and where the restore should happen all the settings are mutual exclusive.
    /// </summary>
    [OutputType]
    public sealed class ScheduleSpecArchiveRestoreMethod
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveRestoreMethodFolder Folder;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveRestoreMethodS3 S3;

        [OutputConstructor]
        private ScheduleSpecArchiveRestoreMethod(
            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveRestoreMethodFolder folder,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveRestoreMethodS3 s3)
        {
            Folder = folder;
            S3 = s3;
        }
    }
}
