// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    /// <summary>
    /// Backend contains the restic repo where the job should backup to.
    /// </summary>
    [OutputType]
    public sealed class ScheduleSpecArchiveBackend
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendAzure Azure;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendB2 B2;
        /// <summary>
        /// EnvFrom adds all environment variables from a an external source to the Restic job.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendEnvFrom> EnvFrom;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendGcs Gcs;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendLocal Local;
        /// <summary>
        /// RepoPasswordSecretRef references a secret key to look up the restic repository password
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendRepoPasswordSecretRef RepoPasswordSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendRest Rest;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendS3 S3;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendSwift Swift;

        [OutputConstructor]
        private ScheduleSpecArchiveBackend(
            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendAzure azure,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendB2 b2,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendEnvFrom> envFrom,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendGcs gcs,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendLocal local,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendRepoPasswordSecretRef repoPasswordSecretRef,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendRest rest,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendS3 s3,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecArchiveBackendSwift swift)
        {
            Azure = azure;
            B2 = b2;
            EnvFrom = envFrom;
            Gcs = gcs;
            Local = local;
            RepoPasswordSecretRef = repoPasswordSecretRef;
            Rest = rest;
            S3 = s3;
            Swift = swift;
        }
    }
}
