// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    [OutputType]
    public sealed class ScheduleSpecCheckBackendGcs
    {
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecCheckBackendGcsAccessTokenSecretRef AccessTokenSecretRef;
        public readonly string Bucket;
        /// <summary>
        /// SecretKeySelector selects a key of a Secret.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecCheckBackendGcsProjectIDSecretRef ProjectIDSecretRef;

        [OutputConstructor]
        private ScheduleSpecCheckBackendGcs(
            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecCheckBackendGcsAccessTokenSecretRef accessTokenSecretRef,

            string bucket,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecCheckBackendGcsProjectIDSecretRef projectIDSecretRef)
        {
            AccessTokenSecretRef = accessTokenSecretRef;
            Bucket = bucket;
            ProjectIDSecretRef = projectIDSecretRef;
        }
    }
}
