// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    /// <summary>
    /// Backend contains the restic repo where the job should backup to.
    /// </summary>
    [OutputType]
    public sealed class ScheduleSpecRestoreBackend
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendAzure Azure;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendB2 B2;
        /// <summary>
        /// EnvFrom adds all environment variables from a an external source to the Restic job.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendEnvFrom> EnvFrom;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendGcs Gcs;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendLocal Local;
        /// <summary>
        /// RepoPasswordSecretRef references a secret key to look up the restic repository password
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendRepoPasswordSecretRef RepoPasswordSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendRest Rest;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendS3 S3;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendSwift Swift;

        [OutputConstructor]
        private ScheduleSpecRestoreBackend(
            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendAzure azure,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendB2 b2,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendEnvFrom> envFrom,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendGcs gcs,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendLocal local,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendRepoPasswordSecretRef repoPasswordSecretRef,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendRest rest,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendS3 s3,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecRestoreBackendSwift swift)
        {
            Azure = azure;
            B2 = b2;
            EnvFrom = envFrom;
            Gcs = gcs;
            Local = local;
            RepoPasswordSecretRef = repoPasswordSecretRef;
            Rest = rest;
            S3 = s3;
            Swift = swift;
        }
    }
}
