// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8up.V1
{

    /// <summary>
    /// Backend allows configuring several backend implementations. It is expected that users only configure one storage type.
    /// </summary>
    [OutputType]
    public sealed class ScheduleSpecBackend
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendAzure Azure;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendB2 B2;
        /// <summary>
        /// EnvFrom adds all environment variables from a an external source to the Restic job.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendEnvFrom> EnvFrom;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendGcs Gcs;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendLocal Local;
        /// <summary>
        /// RepoPasswordSecretRef references a secret key to look up the restic repository password
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendRepoPasswordSecretRef RepoPasswordSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendRest Rest;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendS3 S3;
        public readonly Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendSwift Swift;

        [OutputConstructor]
        private ScheduleSpecBackend(
            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendAzure azure,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendB2 b2,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendEnvFrom> envFrom,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendGcs gcs,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendLocal local,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendRepoPasswordSecretRef repoPasswordSecretRef,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendRest rest,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendS3 s3,

            Pulumi.Kubernetes.Types.Outputs.K8up.V1.ScheduleSpecBackendSwift swift)
        {
            Azure = azure;
            B2 = b2;
            EnvFrom = envFrom;
            Gcs = gcs;
            Local = local;
            RepoPasswordSecretRef = repoPasswordSecretRef;
            Rest = rest;
            S3 = s3;
            Swift = swift;
        }
    }
}
