---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radarr
resources:
  - ../../base
  - pv-downloads.yaml
  - pvc-downloads.yaml
  - pv-movies.yaml
  - pvc-movies.yaml
  - radarr.yaml
  - ingress.yaml
  - restic-credentials.sealed.yaml
  - backup.yaml
