---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-radarr-movies
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: e88c01d4-da67-4d8c-bb43-d57e44adb037
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/movies
      node_attach_driver: nfs
      provisioner_driver: node-manual
