---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-downloads
spec:
  storageClassName: ""
  volumeName: pv-radarr-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti

