---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restic-credentials
  namespace: radarr
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCoSGZXN82yx5LphDr29S1YP6ak1NTsqnQbCiYMqC5QzXumrQ2wbeXPX7GX5f+hSa/2GHAnuiOMf1go7K65B+eeKM51fnfKjWsoqe7MX7pQ8qygF94svDytPevKmu8xERK6cG02r1fVjV36Tdx2Yzhtf3poGJ5akQ8e1V7YRhp2wL7E4DAc4EgvIjrjhjpzhsOzr91Tuvf8MBaKClaYUZiC4NdEbUp8PEhXyPsnu8kPMVzWlAZGebiJV4P/W+CfwWMfAveZmj/QSUaUAfd+KreJcX98kEbTL8i4pIsZ0mKiHeC1vOV6JuJ/Ju64YKO5uITiJrylIcqoDxQsKxfEZWGVX2M2zHjzC7AZxPVwxCzfh2BMYvrB9e/51xqOn8BsUZD16Ol7LXGDNEpU2FgrncO5pBjTXueFfTo0o96wP/5Rimnvt8jMq5EzmOZqPNdhIwYwxgiUKMvU4j/5nRialHtwc6TZQPmezLJyXq5bC+ohNfINLH24wDiLyXbPICn2hmVVDn1DQG2jPhjnViLPpQLPB4dZVEoso3avaZbs34kaM7mMkdLbIxga9U1fgzpCCD2ea5KGnftf5wrNCP5tkRKQTzWCcxAA4PWCIyakW6dgVk/kpVL+cBgpM1RDd42dTux0eyGIxyxysoNFloRwLSVbL0+5nc8Fy5Yu2WSUy83r0Hohr68cveo4ifzMPLGo9GM3tpLdf9YkM5XFMBqoM7LrDOWsfJLGQ85C
    RESTIC_REPOSITORY: AgCn2gxLOW4+pl1Q1H+8l4O59QGI4nkVRLOu5GziLt41b/KT+Ar8wxmGfN1zzjzfs5DZRJzDYg4K8hD2sXRfy8gfA0ZVOd+f4AVgg4kk56XFbLucLetzUZw/HpfUyl8uD+PA5g6Ak+9Tn87BJu3P4sU/p/MQXKFg0Tnm8HASHSp5gj6vvVlCrIb50h8vUdjz82KZXQF+3yoTPa45WeZgyKtDSgDIHJLDN2FczVbmYiuOWcGBpu5YhACIFGkdNyKGQK+wb+hzClUGiybN5UJMeLtG50pPXbJXAM5vjmoP17dXFlxnFsrGVqxRZsDqo0C2q4BlvFcxGBI1vMgB7yTIo0jp4JIPd95/vaGuwvathBrbSCeTUHoso+dMt4DVorjTJ1xGKaL9YTplnI0gliyGXzGkOQ9hEvW/pb4urLfunZvbYWRVnNItcavKV0IZJaecBHfEBmkUp8sBN5mSRWrH8Bnixpu8MFxd95Qrd5psXZa0Hr5PYNg/9lxyl7T/TvbAWz5iBHarEjE2wzUK99XZ4ZjeP1vCkSADIUysC/9uyH+QQoWw65VpP/mHEzYqpYJxUcoiJEOxPiDkGcni9wKKMcUXKsrdAX9d0IyVm0OobB5B05ZzaT5MtBMpt8Gx5ya2kUDnTD7CsdU71NAJQcd4TxK3LSKkPPgrIKnwVy2ne9oqG2ssbFL61BE6K9Y5oiz3Pgn6a9xXXGY28jmgPZ3k0kEuM18MBJufqx6OxR7jXpWi/H8XJ+UyCyTvXODjgfRxo9Lt38cky2otPs0V6+oqdaahkA==
  template:
    metadata:
      creationTimestamp: null
      name: restic-credentials
      namespace: radarr
    type: Opaque
