---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarr
resources:
  - ../../base
  - pv-downloads.yaml
  - pvc-downloads.yaml
  - pv-tv.yaml
  - pvc-tv.yaml
  - sonarr.yaml
  - ingress.yaml
  - restic-credentials.sealed.yaml
  - backup.yaml
