---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarr-tv
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: ca4cb233-0c62-490f-83ac-d9e0678cff22
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/tv
      node_attach_driver: nfs
      provisioner_driver: node-manual
