---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-downloads
spec:
  storageClassName: ""
  volumeName: pv-sonarr-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti

