apiVersion: v1
kind: Secret
metadata:
    name: restic-credentials
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:hD5L7ntnUHHE/j0Cp+onMv3sGx8r1pcdEg2qh9gpFzMML23xPHcOXQnB0qTppeaRZZesdLMZe+oXJvBeEC9+DnE=,iv:5CdvnismFg0PfcqjC5i5x7YGS9F9EJNXKr893SWNMiM=,tag:p3zQQbD+SsQK73/wO4fFxA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PE2gF7h8qAZ3KZk+TXNLiHQjNqNZlPTddg==,iv:KzJs95eN8dj0AxMHHzAfYzz7qZaz0rsTE+71u12n218=,tag:WIWLLITDfNYyEECtMJYTnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxmmkdzm0gas4z03q6mnzcv5exs7wlxjxrp8qzh0eujzqk8wvvyqk3qcjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNWhNRjZwWXJwUHdQOGZv
            MEVnRHh0MDF4ZENRNlo4Ty9VNHpVU0xFN2dBCjU3M1NNQkRIeHlUNm9OSnlsREJP
            TjJSM2NDOS9STlVQWFlxdDlWbjJsaWcKLS0tIHZWdVB1ODlVTkJBTHVEODdjc1Z4
            dGJjTlhNN2dhUE9DOTlqaGozbnczMWcK25muplBNeJbiHy/e1SkE7Uoh9lqHQdYx
            FrRAr0D95TyeYP+ELy18ad9JCquBFSDlOTt+tkTODQVXwS9PyJHm2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qkxcnuwjvme9667c763xpxjedfyxjpgl09msty80esrf3fuj45cqeh9v6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV0dlMzVXcWc4OW9kTldr
            Vjl1SXpFZWNkenV4djlDN3paMnplaW9uZmdRCm9QLzd1UUVJL3c4Vmd6cFJkN1BF
            Tnd5WndVUFIwQ0NZZ2lUTjRPOEwvVkkKLS0tIG9EUENYMFBXV2JQd3RmVzA5OG1l
            TlUzQitEKzhKeVRyVm9ORXNBRkFHb2cKYq4MazHXJontgwlChno1q37ASsynbdJa
            hqMxCjP7wP17uo/JH4LDEZf4g4dP33qkuKegNlMU2OeLb09nVgRThQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T12:55:01Z"
    mac: ENC[AES256_GCM,data:RGFP74t7oevJGxvWJyc/3wqzJJmvT2kJdUf593qZtS/R0afYtlZChYIEeyp/AKWvdPLAp/A+6OsUn0ISr9jGpz4ogup48KYUGiu5PdKlR/ttLHsLq4FBNyU0YtteMYe5KD3NU0i5p+CYHjXvHpgtUtWrglUaXc7h/LucBoHD0rM=,iv:i+FudLqVh0K5jzuUgLjLSqXVmVM+/UJ6XElqL9UhC3s=,tag:GiBB9X7EWKD2oX2CoBSfKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
