---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.13.2
    helm:
      releaseName: cert-manager
      valuesObject:
        installCRDs: true
        dns01RecursiveNameservers: "1.1.1.1:53,9.9.9.9:53"
        dns01RecursiveNameserversOnly: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager

