---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lidarr-music
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: 5a28072f-1e89-4db5-a2ed-7c1e4880995f
    volumeAttributes:
      server: 10.0.60.3
      share: /mnt/tank/music
      node_attach_driver: nfs
      provisioner_driver: node-manual
