---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lidarr-music
spec:
  storageClassName: ""
  volumeName: pv-lidarr-music
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
